### ISSUE TITLE
请问一下，添加多个PathSimplifier组件，后面的组件数据会越叠越多怎么解决？

### ISSUE THREAD

**Issue by liyue118** [ElemeFE/react-amap#100]
`<Map zoom={14} useAMapUI >
              <GisPathZ  data={getGisPathZ} color={'green'}/>
              <GisPathB  data={getGisPathB} color={'yellow'}/>
              <GisPathC  data={getGisPathC} color={'orange'}/>
              <GisPathD  data={getGisPathD} color={'red'}/>
              <GisPoint data={getGisPoint}/>
/Map>`
因为每一个data数据和颜色都不一样，所以我写了四个组件，每次props重渲染都会导致数据变多，我在每个里面添加了shouldComponentUpdate返回true,单个组件数据都没问题，一起的时候后面的组件数据会翻倍翻倍的叠，请问这个怎么解决？

**Comment by helloalexian** [comment]
這個是由於組件更新導致創建了許多重複的pathSimplifier的實例導致的吧，高得官方有一些例子可以找一下，注意不要讓組件更新重複創建pathSimplifier就可以
