### ISSUE TITLE
如何自定义规划一个路线图？

### ISSUE THREAD

**Issue by frank994** [ElemeFE/react-amap#103]
我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。

想要写出一个自定义的路线规划图，或轨迹图，但是没有思路，能麻烦提供一些思路吗，就够了，谢谢。

**Comment by frank994** [comment]
已经在官网找到轨迹回放图，谢谢。

**Comment by Croash** [comment]
@frank994 
https://github.com/ElemeFE/react-amap/blob/0fb413cb4207deb27bed6856e514b040386f33a3/components/map/demo/amapui.md
类似这样的，修改load的内容和配置项即可
或者可以看一下这个 https://github.com/Croash/react-amapui-wrapper

**Comment by frank994** [comment]
@Croash 遇到一个问题，在使用this.props.__map__时出错，undefined

**Comment by frank994** [comment]
@Croash 解决了，谢谢了，看了一下源码
