### ISSUE TITLE
AMap.Geocoder可以在react-amap里面使用吗？如何使用？

### ISSUE THREAD

**Issue by Dorisfeng** [ElemeFE/react-amap#106]
+ [ ] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [ ] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

**Comment by ioslh** [comment]
https://github.com/ElemeFE/react-amap/issues/12

**Comment by ttylikl** [comment]
我做了个Autocomplete的react-amap自定义组件，在里面有使用Geocoder的示例。你可以checkout代码看看： https://github.com/ttylikl/react-amap-plugin-autocomplete
