### ISSUE TITLE
高德自v1.4.4新增货车路线规划，能否进行更新

### ISSUE THREAD

**Issue by gycsee** [ElemeFE/react-amap#108]
-  [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+  [ ] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+  [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### What is Expected?
更新到最新v1.4.6, 并新增驾车路线规划服务、货车路线规划服务、公交换乘服务、步行导航服务

#### What is actually happening?
暂时只支持驾车路线规划服务（AMap.Driving）

**Comment by superlbr** [comment]
参考 https://github.com/ElemeFE/react-amap/issues/94 ，指定version
```
<Map version="1.4.4">
    ....
</Map>
```
