### ISSUE TITLE
急急急！！！如何实现在一个页面有多个地图（个数不定），且每个地图不受影响事件events怎么摘出来，然后传参数e和Id

### ISSUE THREAD

**Issue by gy029** [ElemeFE/react-amap#109]
+ [ ] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [ ] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

**Comment by ioslh** [comment]
> 事件events摘出来

这个是什么意思啊？一个页面多个地图这个应该没什么问题，[文档站](https://elemefe.github.io/react-amap/components/map)全是一个页面好多地图。
