### ISSUE TITLE
关于markers，在地图上，如何确定是哪个marker被点击了

### ISSUE THREAD

**Issue by Mantak** [ElemeFE/react-amap#11]
<Markers 
          markers={this.markers}
 />
当点击 marker的时候，能获取该marker在markers里面的index吗？

或者如何在marker里添加除了坐标之外的额外信息，并且通过marker的click事件来获取

**Comment by ioslh** [comment]
抱歉，这是我文档写的不够周全；我写了个 jsfiddle 示例来演示如何确定点击的 marker。

https://jsfiddle.net/h4u8mdng/12/

如果还有疑问随时欢迎回复。

**Comment by ioslh** [comment]
相应的文档已更新 https://elemefe.github.io/react-amap/components/markers

**Comment by Mantak** [comment]
厉害了我的哥，今天只是来看看有没有答案，没想到昨天就有了答案。由衷的感谢～～～

我看了一下文档，建议把“在回调里我们可以获得全部的原始数据”，改为“在回调里我们可以通过.getExtData()获得全部的原始数据”。

对于markers，我目前了解的只是一个包含了很多对象的数组，而每个对象必须包含一个position的对象属性，其他的属性，可以带入任意想要包含的信息。所有的信息都可以通过marker.getExtData()来获取。坐标还可以通过marker.getPosition()来获取

我也是刚接触amap。 现在我了解了marker有两个方法getPosition getExtData。 如果能有个文档，把marker以及其他对象的actions都列出来就完美了

**Comment by ioslh** [comment]
`getPosition` 和 `getExtData` 都是高德地图 API 创建的 Marker 实例上的方法，全部的方法在[高德官方文档](http://lbs.amap.com/api/javascript-api/reference/overlay#Marker)都比较齐全，所以我这里的文档没细写这些。

> 对于markers，我目前了解的只是一个包含了很多对象的数组，而每个对象必须包含一个position的对象属性，其他的属性，可以带入任意想要包含的信息。所有的信息都可以通过marker.getExtData()来获取。坐标还可以通过marker.getPosition()来获取

你的理解没错，是这样的。你的描述比较容易理解，我再斟酌一下文档的语言描述，谢谢你。
