### ISSUE TITLE
使用时一定需要key值么？key值会过期么 ？

### ISSUE THREAD

**Issue by 341502** [ElemeFE/react-amap#113]
+ [ ] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### What is Expected?
查看高德Api发现，存在key值，但是Marker等组件上没有发现key值，请问，是否需要key值，key值申请以后会不会过期？

**Comment by ioslh** [comment]
这个 Key 是高德给开发者分配的，可以在[高德开放平台](http://lbs.amap.com/faq/account/key/67)申请你自己的 Key。一般一个 key 对应你自己的一个应用，用来统计数据之类的作用。
