### ISSUE TITLE
如果判断指定gps坐标点是否在画出的circle内？

### ISSUE THREAD

**Issue by helloalexian** [ElemeFE/react-amap#114]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### What is Expected?
根据Circle组件，可以画出一个圆图形，包含中心点GPS坐标与半径；
但是如何判定指定的一个新GPS坐标是否被当前圆包含？

https://elemefe.github.io/react-amap/components/circle
API的接口内没想找到相关的内容，我又觉得如果使用circle组件的话，这个判定指定点是否在圆内的功能可能是一个基础功能，可否帮忙解答一下，感谢~

**Comment by ioslh** [comment]
Circle 实例有个 contains 方法，判断指定点坐标是否在圆内。文档 http://lbs.amap.com/api/javascript-api/reference/overlay#circle
