### ISSUE TITLE
OverlayGroup类如何在react-amap中使用？

### ISSUE THREAD

**Issue by xueguozhongli** [ElemeFE/react-amap#116]
this.mapEvents = {
			created:(map) => {
				this.amap = map;
		                this.layers = [];
				let polygons = [];
				if(this.amap && this.props.layers.length>0){
					this.layers = this.props.layers;
					this.layers.forEach((item,index)=>{
					    let polygonArr = item;
					    let polygon = new AMap.Polygon({
					        path: polygonArr,//设置多边形边界路径
					        strokeColor: "#FF33FF", //线颜色
					        strokeOpacity: 0.4, //线透明度
					        strokeWeight: 3,    //线宽
					        fillColor: "#1791fc", //填充色
					        fillOpacity: 0.35//填充透明度
					    });
					    polygons.push(polygon);
					});

					let overlayGroup = new AMap.OverlayGroup(polygons);
					if(this.props.showMap.includes("HOTSPOT")){
						overlayGroup.show();
					    //polygon.setMap(this.amap);
					}else if(!this.props.showMap.includes("HOTSPOT")){
						overlayGroup.hide();
					}
				}
			}
                }

**Comment by xueguozhongli** [comment]
结果证明是引用amap的版本问题，将
https://webapi.amap.com/maps?v=1.4.0
的版本修改为v=1.4.6后，不再报错，额，，，

**Comment by miaosongjing** [comment]
你好，我刚开始用地图，有些地方不懂。想请问你一下，引入react-map之后，如果需要调用new AMap.geo.…的话还要引入amap吗

**Comment by superlbr** [comment]
如果遇到add方法会报错，检查传入OverlayGroup的覆盖物坐标格式，需要这样new AMap.LngLat()
