### ISSUE TITLE
使所有的点标记同时显示在视野内，并且设置中心点

### ISSUE THREAD

**Issue by 341502** [ElemeFE/react-amap#117]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [ ] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### Reproduce Example Link or Code Fragment
需要画出一个人一天内的运动轨迹，一天会有多对经纬度，如何使得这些数据都在视野内，如何设置中心点？zoom 比例 需要改变么？

**Comment by ioslh** [comment]
可以试试获取到地图实例后，调用 setFitView 方法。

**Comment by 341502** [comment]
谢谢你~地图 zoom、center属性去除即可自动进行中数据点在视野范围内。【react-amap框架汇总未找到setFitView 】

**Comment by xiaoxingchao** [comment]
zoom、center属性去除，就变成默认的了，你是怎么解决自动调整的

**Comment by Symous** [comment]
有需要的老哥参考这里：#52 。
