### ISSUE TITLE
请问我应该如何使用AMap.Geocoder

### ISSUE THREAD

**Issue by wanghuida** [ElemeFE/react-amap#12]
我需要实现一个官方的例子：http://lbs.amap.com/fn/jsdemo_loader/?url=http%3A%2F%2Fwebapi.amap.com%2Fdemos%2Fgeocoder%2Fgeocoder-regeo.html

**Comment by ioslh** [comment]
react-amap 目前没有实现 AMap.Geocoder  组件的封装；对于这些组件，你可以在我们 Map 组件的 created 事件里自行创建，这个 created 方法被调用时可以确保高德地图 的 API 接口加载成功了，可以放心使用全局的 AMap 变量。

参考[对于我们尚未提供的组件，你也完全可以在地图的实例创建成功后，亲自调用高德的实例化方法进行创建](https://elemefe.github.io/react-amap/articles/high)

我写了示例，你看是不是你想要的效果 https://jsfiddle.net/h4u8mdng/14/

**Comment by wanghuida** [comment]
我测试了一下，用你的方法已经解决了我的问题，谢谢。

**Comment by yangmingfa** [comment]
请问为什么我在导入react-amap以后,在created中拿不到AMap实例呢?一调用这个就报错,说是no defined,求大神解答,急!!感谢感谢感谢.

**Comment by tz198849** [comment]
@wanghuida 
您好，朋友，请问您是如何实现的。react-amap 的示例也打不开。您能提供个示例吗？  我想在 组件中使用  AMap.Driving

**Comment by wyxt81** [comment]
在create里拿不到Amap，用window.AMap可以拿到

**Comment by lihua111** [comment]
想要实现高德地图的输入提示后查询，主要用到 AMap.Autocomplete，AMap.PlaceSearch两个插件，在created引入以后，触发事件，不知道写在哪里，感觉没有触发到map的其他事件，求指教

**Comment by Twiner94** [comment]
react-amap 中调用AMap.Geocoder实例的getLocation方法获取的坐标与高德解析的坐标误差特别大？这是什么原因

**Comment by bojhkaka** [comment]
您好，这个AMap.Geocoder事例打不开，请问可以贴一下是如何实现的吗，我想要使用AMap.DistrictLayer.Country，盼回复，谢谢

**Comment by ttylikl** [comment]
写了个react-amap的插件: react-amap-plugin-autocomplete，里面有用Geocoder。 https://github.com/ttylikl/react-amap-plugin-autocomplete

**Comment by zhaosheng808** [comment]
请问一下怎么获取国外的地址呢？demo只能查询国内的坐标详细地址

**Comment by gx191179173** [comment]
请问怎么实现搜索功能，能切换城市的

**Comment by xc2f** [comment]
> 您好，这个AMap.Geocoder事例打不开，请问可以贴一下是如何实现的吗，我想要使用AMap.DistrictLayer.Country，盼回复，谢谢

你好，实现了吗，我取AMap，里面没有DistrictLayer这个属性

**Comment by zhangzhen6** [comment]
请问如何处理只展示在Circle范围内的Marker

**Comment by xu-Aurora** [comment]
请问解决了了？怎么调用Geocoder实现地址解析成坐标

**Comment by xu-Aurora** [comment]
> react-amap 目前没有实现 AMap.Geocoder 组件的封装；对于这些组件，你可以在我们 Map 组件的 created 事件里自行创建，这个 created 方法被调用时可以确保高德地图 的 API 接口加载成功了，可以放心使用全局的 AMap 变量。
> 
> 参考[对于我们尚未提供的组件，你也完全可以在地图的实例创建成功后，亲自调用高德的实例化方法进行创建](https://elemefe.github.io/react-amap/articles/high)
> 
> 我写了示例，你看是不是你想要的效果 https://jsfiddle.net/h4u8mdng/14/

https://jsfiddle.net/h4u8mdng/14/这地址根本打不开

**Comment by xu-Aurora** [comment]
> https://github.com/ttylikl/react-amap-plugin-autocomplete

你的我进去看了啊，没有看到你怎么用Geocoder啊

**Comment by liao0305** [comment]
> 想要实现高德地图的输入提示后查询，主要用到 AMap.Autocomplete，AMap.PlaceSearch两个插件，在created引入以后，触发事件，不知道写在哪里，感觉没有触发到map的其他事件，求指教
请问解决了吗？我现在也有这样的需求
