### ISSUE TITLE
关于mouseTool.polygon添加事件问题

### ISSUE THREAD

**Issue by programmer-yang** [ElemeFE/react-amap#122]
我需要在使用`mouseTool.polygon`的时候添加鼠标单击事件来判断用户自定义画的这个点是否在合法范围之内
这是我的代码：
```
this.tool.polygon({
  draggable: true,
  events: {
    click: () => {
      console.log('click');
    }
  }
});
```
但他现在不生效
请问正确的使用方式应该是？

**Comment by ioslh** [comment]
在使用 MouseTool 画图形的过程中没法自定义鼠标事件的，高德没有提供这样的接口。参考这个 http://lbs.amap.com/api/javascript-api/reference/plugin#AMap.MouseTool
