### ISSUE TITLE
react-amap如何使用AMap.GeometryUtil.distance,AMap怎么得到呢

### ISSUE THREAD

**Issue by 750973092** [ElemeFE/react-amap#127]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

**Comment by NexxLuo** [comment]
同问，react版本貌似没有集成此库，应该需要单独引入，但是不知道怎么引入到项目中。npm?cdn?

**Comment by frank994** [comment]
window.Amap可以用，作者已经把Amap库挂在到window对象
例子:
```
window.AMapUI.load(['ui/misc/PathSimplifier'], P => {

});
```

**Comment by NexxLuo** [comment]
window下的确有AMap这个对象，但是GeometryUtil在哪？

**Comment by 750973092** [comment]
同问

**Comment by NexxLuo** [comment]
已找到问题所在，我对比了js api中的例子，发现js的引入后面有plugin参数，于是我把Map组件的version写成如下格式，这样就可以一样带上后面写的plugin参数。这样的话应该就可以保持与JS API一样的函数用法。比如图中的CircleEditor
![amap](https://user-images.githubusercontent.com/18549980/42205277-90b2ca9e-7ed6-11e8-93b3-1bbb4f9abe09.png)

![amap2](https://user-images.githubusercontent.com/18549980/42205413-06c71ec4-7ed7-11e8-8d22-db5b8dde7543.png)

但是我不知道为什么这样写的同时GeometryUtil 也有了，可能是依赖把

**Comment by BaoXuebin** [comment]
`react-amap` 默认的 高德 版本是 `1.4.0`。
```
// react-amap/components/utils/APILoader.js
const DEFAULT_CONFIG = {
  v: '1.4.0',
  hostAndPath: 'webapi.amap.com/maps',
  key: 'f97efc35164149d0c0f299e7a8adb3d2',
  callback: '__amap_init_callback',
  useAMapUI: false
}
```
而 `AMap.GeometryUtil` 是 `1.4.2` 才引入的。

`Map` 组件定义了 `version` 属性。

```
// react-amap/components/map/index.js
if (typeof window !== 'undefined') {
      this.pluginMap = {}
      new APILoader({
        key: props.amapkey,
        useAMapUI: props.useAMapUI,
        version: props.version,
        protocol: props.protocol
      }).load().then(() => {
        this.createInstance()
        if (!this.state.mapLoaded) {
          this.setState({
            mapLoaded: true
          })
        }
      })
    }
```
所以可以这样使用：
```
<Map
    zoom={12}
    version={'1.4.2'} // 指定版本
    mapStyle={theme}
    loading={<Loading />}
    plugins={this.plugins}
    events={this.amapEvents}
>
```

**需要注意的是，版本不同导致有部分组件的使用方法不一样，可能会导致之前的代码错误。**

**Comment by luofly** [comment]
我用的1.4.4
