### ISSUE TITLE
样式文件加载错误

### ISSUE THREAD

**Issue by sugarPro** [ElemeFE/react-amap#13]
npm install后，引入地图会有错误，提示lib中的css文件不能加载

**Comment by ioslh** [comment]
信息能详细一点吗？
1. 引用的是哪个版本的 react-amap？ 
2. 怎么加载的？你的项目的运行环境？
3. 具体的报错信息？
4. 相关的代码能贴上来吗？

**Comment by sugarPro** [comment]
react-amap版本是0.2.6
react-imvc+webpack
错误信息是
ERROR in ./~/react-amap/lib/_assets/marker.css
Module parse failed: D:\localtone\node_modules\react-amap\lib\_assets\marker.css Unexpected token (1:0)
You may need an appropriate loader to handle this file type.
具体代码很简单，在某个react组件中import amap是就会出错

btw: 多谢你的回复，小白一只

**Comment by ioslh** [comment]
hi，你可以尝试安装 `style-loader` 和 `css-loader` 并在 webpack 的配置文件中使用：
```
  module: {
    loaders: [ 
      {
        test: /\.css$/,
        loader: ['style-loader', 'css-loader']
      }
    ]
  }
```

原因是在组件 Markers 里 require 了一个 css 文件，如果你没有安装 css loader 那么 webpack 不知道如何处理这个文件的。很抱歉，稍后我会重发一个版本修复这个问题。在发布之前你可以通过安装  `style-loader`, `css-loader` 的方式来解决。

**Comment by sugarPro** [comment]
由于项目本身限制，我暂时引入了地图的CDN库，没有使用您的插件了，非常感谢你的帮助

**Comment by ioslh** [comment]
[v0.2.7](https://github.com/ElemeFE/react-amap/releases/tag/v0.2.7)
