### ISSUE TITLE
如何设置默认图层为TileLayer.Satellite

### ISSUE THREAD

**Issue by schbook** [ElemeFE/react-amap#131]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [] 我写了个问题重现的例子，链接或者代码将会贴在下面。

map组件的defaultLayer中有这样一个说明："当前地图中默认显示的图层。默认图层可以是TileLayer.Satellite等切片地图，也可以是通过TileLayer自定义的切片图层"。
不知道如何设置默认图层为TileLayer.Satellite，可否提供一个例子。

**Comment by Huibean** [comment]
plugins 里面这样写可以设置默认为卫星地图
```javascript
  const plugins = [
      {
        name: 'MapType',
        options: {
          defaultType: 1
        }
      },
  ]
```

**Comment by meitingshuoguo** [comment]
这个方法并不好，这个是用来加载高德自带的图层切换的插件的，虽然目的达到了，但实际上用这个并不太合适，正常情况下应该还是设置map的layers属性，但那个时候还没window.AMap对象，没办法把那两个图层对象的实例放进去。
我现在也想默认加载卫星图，但是没找到别的办法，是不是目前只能这样了
