### ISSUE TITLE
浏览器定位，怎么设置

### ISSUE THREAD

**Issue by yahengqi** [ElemeFE/react-amap#135]
+ [ ] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

**Comment by yahengqi** [comment]
import * as React from 'react';

import { Map } from 'react-amap';



class ClougMapCom extends React.PureComponent<any>{
    
    constructor(props: any){
        super(props);
        this.state={position:[0,0]}
    }
    
    render(){
        const onComplete=(data:any)=>{
            console.log(data+'===090909');
            this.setState({
                position:[data.position.getLng(),data.position.getLat()]
            })
        };
        const onError = ()=>{
            alert('定位失败');
            // that.setState({
            //     position:[112.58032,37.857965]
            // })
        };

        const events = {
            created: (instance:any,window:any) => {
                console.log(instance+'====='+window+'===123');
                instance.plugin('AMap.Geolocation',  ()=> {
                    const geolocation = new window.AMap.Geolocation({
                        enableHighAccuracy: true,//是否使用高精度定位，默认:true
                        timeout: 10000,          //超过10秒后停止定位，默认：无穷大
                        maximumAge: 0,           //定位结果缓存0毫秒，默认：0
                        convert: true,           //自动偏移坐标，偏移后的坐标为高德坐标，默认：true
                        showButton: true,        //显示定位按钮，默认：true
                        buttonPosition: 'RB',    //定位按钮停靠位置，默认：'LB'，左下角
                        buttonOffset: new window.AMap.Pixel(14, 130),//定位按钮与设置的停靠位置的偏移量，默认：Pixel(10, 20)
                        showMarker: false,        //定位成功后在定位到的位置显示点标记，默认：true
                        showCircle: false,        //定位成功后用圆圈表示定位精度范围，默认：true
                        panToLocation: true,     //定位成功后将定位到的位置作为地图中心点，默认：true
                        zoomToAccuracy:true      //定位成功后调整地图视野范围使定位位置及精度范围视野内可见，默认：false
                    });
                    instance.addControl(geolocation);
                    geolocation.getCurrentPosition();
                    window.AMap.event.addListener(geolocation, 'complete', onComplete);//返回定位信息
                    window.AMap.event.addListener(geolocation, 'error', onError);      //返回定位出错信息
                });
            }
        };
        
        return (
            <Map amapkey={''}
                plugins={['Scale','ToolBar']}
                zoom={16}
                events={events}
            /> 
                
            
        );
    }
}

export default ClougMapCom;


在pc上无法自动定位到当前地址

**Comment by luofly** [comment]
要用https
