### ISSUE TITLE
Markers组件render属性没有更新

### ISSUE THREAD

**Issue by 750973092** [ElemeFE/react-amap#138]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [x] 我写了个问题重现的例子，链接或者代码将会贴在下面。

Markers组件中的markers更新的时候render属性的自定义组件没变化，打印了下没调用render中的方法，
因为我的render属性中的样式是根据markers的变化而变化的

#### Reproduce Example Link or Code Fragment
```
const renderMarkerLayout=(extData)=> {
      console.log(333322111)
      return (
        zoom == 13 || zoom === 10 ?
          <div className={styles.markerLayout}>{extData.mylabel}</div> :
          <div
            className={`${styles.markerLayout15} ${extData.checked ? styles.markerLayout15Checked : ''}`}>{extData.mylabel}
            ({extData.num}套)</div>
      )
    }
    return (
      <>
        <div className={styles.mapTop}><div onClick={()=>this.goback()} className={styles.goback}><i></i>返回</div><div className={styles.right}><i></i></div></div>
        <Map  {...mapProps}>
          <Marker position={location}><img src={pin} alt=""/></Marker>
          <Markers
            events={this.markersEvents}
            render={renderMarkerLayout}
            markers={markers}
            //useCluster={this.state.useCluster}

          />

        </Map>
      </>
```

**Comment by Dorisfeng** [comment]
同样的问题，render函数只在初始化的时候执行一遍，我要实现的效果是随着放大级别变化，改变点坐标样式，解决方法是
 zoomchange:(e)=>{
            // console.log(e)
            let nowZoom=this.state.map.getZoom()
            this.setState({nowZoom,markers:this.state.markers.slice(0)}
            })


        }

**Comment by zim-lee** [comment]
解决了么，我也遇到了，markers数据更新了，Makers组件不重新渲染，render也不执行

**Comment by caosaiqi** [comment]
同问

**Comment by yjgeek** [comment]
数据不同就可以了，如: JSON.parse(JSON.stringify([]))

**Comment by ioslh** [comment]
```
<Markers
            events={this.markersEvents}
            render={renderMarkerLayout}
            markers={markers}
            //useCluster={this.state.useCluster}

          />
```
猜测可能是这里的 `markers` 引用并没有变更

**Comment by demon-zhonglin** [comment]
> ```
> <Markers
>             events={this.markersEvents}
>             render={renderMarkerLayout}
>             markers={markers}
>             //useCluster={this.state.useCluster}
> 
>           />
> ```
> 
> 猜测可能是这里的 `markers` 引用并没有变更

同问，我的markers 数据在this.state里面，constructor时其值设为[]，componentDidMount时从后端获取的数据并更新 markers, 但还是没变化。
