### ISSUE TITLE
react-amap  中调用AMap.Geocoder实例的getLocation方法获取的坐标与高德解析的坐标误差特别大？这是什么原因

### ISSUE THREAD

**Issue by Twiner94** [ElemeFE/react-amap#139]
+ [ ] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [ ] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

**Comment by Twiner94** [comment]
"广东深圳龙华新区,西头新村D区18栋"    调用AMap.Geocoder实例的getLocation方法获取的坐标:113.899992,22.564349    但是高德解析获取的却是114.017033,22.641863

**Comment by liuguicheng** [comment]
这个问题解决了吗？请问
