### ISSUE TITLE
点击marker之后，所有的marker都闪烁一下，marker总数量 > 20

### ISSUE THREAD

**Issue by BigFaceMaster** [ElemeFE/react-amap#142]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### What is Expected?
期望点击marker 其他的marker不闪烁

**Comment by zzswang** [comment]
估计是你点击 marker 的时候，有什么事件，导致 props 或者 state 变了，进而导致了 map 重新 render 了
