### ISSUE TITLE
marker 拖动获得坐标后，再将坐标赋值回去，marker会偏移的问题

### ISSUE THREAD

**Issue by wellenzhong** [ElemeFE/react-amap#143]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### Reproduce Example Link or Code Fragment
有一个功能，可以通过拖动marker来获得进行标，也可以直接输入坐标来直接标注。
当拖动marker时，会将坐标反查出来在input框里，这时，再点一下“button”定位，发现坐标会移动一下。
offset设置过了，无效。多大的值都无效。
`<Map amapkey={'***'} plugins={['ToolBar']} useAMapUI zoom={6} events={mapEvents} >
             <Marker
                                      clickable
                                      events={markerEvents}
                                      draggable
                                      position={markerPosition}
                                      offset={{ x: -10, y: -34 }}
                                    />
                            </Map>`
#### What is Expected?
期望：拖动marker获得坐标后，再点击button定位时，marker不移动。

#### What is actually happening?
问题：点击button来根据坐标来定位时，marker会移动。

**Comment by huyawei** [comment]
同问

**Comment by huyawei** [comment]
@wellenzhong 解决了
dragend给的参数
不要直接使用e.lnglat 这玩意是鼠标的坐标
e.target 是marker本身
const position = e.target.getPosition()

**Comment by wellenzhong** [comment]
后来我也注意到这个问题了。它的坐标点是以鼠标坐标为准的，所以会有偏移。
