### ISSUE TITLE
地址是否可以转换成坐标

### ISSUE THREAD

**Issue by wcircle** [ElemeFE/react-amap#15]
此插件，是否可以实现，给详细地址信息，直接定位到地图的准确位置，如果可以如何实现

**Comment by ioslh** [comment]
通过高德提供的 [AMap.Geocoder](http://lbs.amap.com/api/javascript-api/reference/lnglat-to-address#m_AMap.Geocoder) 接口可以实现，示例参考 http://lbs.amap.com/api/javascript-api/example/geocoder/geocoding/

react-amap 目前没有封装高德的 AMap.Geocoder 组件，但是你可以在 Map 组件的 created 事件中来自己创建 AMap.Geocoder 实例并使用，比如这个 #12 就是这么做的。
