### ISSUE TITLE
InfoWindow手动关闭后无法再次打开

### ISSUE THREAD

**Issue by Symous** [ElemeFE/react-amap#152]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。(**附官方示例**)

#### Reproduce Example Link or Code Fragment
https://elemefe.github.io/react-amap/components/infowindow 
官方infowindow使用方法的第一个代码片段。

#### What is Expected?
当我们点击下方的random position 按钮后，显示infowindow，当我们点击infowindow右上角的关闭图标，后续应该可以继续打开infowindow。

#### What is actually happening?
点击关闭图片，再次点击random position 后，infowindow 不显示。

**Comment by lilyneaoer** [comment]
我也遇到同样的问题了

**Comment by jim-king-2000** [comment]
你要把InfoWindows打开和关闭的状态关联到react的state里，这样就正常了。

**Comment by orangeyyy** [comment]
我遇到的问题是 关闭了infoWindow以后要点击两次triggleVisible才能展开

**Comment by yiqieqie** [comment]
有解法了吗？ 我都是操作两次解的， 但是这样会造成其他问题

**Comment by Symous** [comment]
使用state控制infowindow的显示和隐藏。如果不这样的话关闭窗口后，infowindow就从DOM中移除了，所以无法再显示。

**Comment by yiqieqie** [comment]
> 使用state控制infowindow的显示和隐藏。如果不这样的话关闭窗口后，infowindow就从DOM中移除了，所以无法再显示。

就是使用state控制的visible

**Comment by ioslh** [comment]
1. 自己用一个 state 实现显示和隐藏状态切换；
2. 要么隐藏高德自己给 InfoWindow 加的关闭按钮；要么自己再监听窗口的 close 事件，触发时同步改变 state

**Comment by vmto** [comment]
> > 使用state控制infowindow的显示和隐藏。如果不这样的话关闭窗口后，infowindow就从DOM中移除了，所以无法再显示。
> 
> 就是使用state控制的visible

我也遇见了这样的麻烦，不过我解决了，
const [visible, setVisible] = useState(false)，
点击时：setVisible(true)，
同时events={close:()=>{setVisible(false)}}
