### ISSUE TITLE
轨迹回放功能使用报错

### ISSUE THREAD

**Issue by wupengju** [ElemeFE/react-amap#153]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### Reproduce Example Link or Code Fragment
Throw Error Code：
```
    const events = {
      created: (marker) => {
        console.log('marker created');
        this.curDeviceMarker = marker;
        this.map.setFitView(marker);
      }
    };
   // ...
   this.curDeviceMarker.moveAlong(lineArr, 200);
```

#### What is Expected?
高德官网demo：
https://lbs.amap.com/api/javascript-api/example/marker/replaying-historical-running-data

#### What is actually happening?
![image](https://user-images.githubusercontent.com/16716231/48119947-a3314400-e2ab-11e8-9c94-989f2a514c58.png)

**Comment by JunCxio** [comment]
我也遇到这个问题..请问已经找到解决的方法吗

**Comment by luweiCN** [comment]
我也遇到这个问题..请问已经找到解决的方法吗

**Comment by hanl754** [comment]
@jin006s  问题和你类似，参考了https://github.com/ElemeFE/react-amap/issues/68 lineArr使用AMap经纬度的包装类型就正常了。
参考：
``` javascript
buildLineArr() {
  	const lineArr =[]
    let lngX = 116.397428, latY = 39.90923;        
    lineArr.push(new AMap.LngLat(lngX, latY));
    for (let i = 1; i < 4; i++) {
      lngX = lngX + Math.random() * 0.05;
      if (i % 2) {
        latY = latY + Math.random() * 0.0001;
      } else {
        latY = latY + Math.random() * 0.06;
      }
      lineArr.push(new AMap.LngLat(lngX, latY));
    }
    return lineArr
  }

**Comment by JunCxio** [comment]
感谢


| |
林锦焕
|
|
jin006s@163.com
|
签名由网易邮箱大师定制
在2019年3月20日 14:59，han<notifications@github.com> 写道：

问题和你类似，参考了#68 lineArr使用AMap经纬度的包装类型就正常了。
参考：

buildLineArr() {

  	constlineArr=[]

    let lngX =116.397428, latY =39.90923;        

    lineArr.push(newAMap.LngLat(lngX, latY));

    for (let i =1; i <4; i++) {

      lngX = lngX +Math.random() *0.05;

      if (i %2) {

        latY = latY +Math.random() *0.0001;

      } else {

        latY = latY +Math.random() *0.06;

      }

      lineArr.push(newAMap.LngLat(lngX, latY));

    }

    return lineArr

  }
