### ISSUE TITLE
如何调用转换坐标系的函数

### ISSUE THREAD

**Issue by yutao98712** [ElemeFE/react-amap#155]
![image](https://user-images.githubusercontent.com/20662809/48884078-d0f6bb00-ee5d-11e8-9a0e-31f042b6e950.png)

**Comment by lilyneaoer** [comment]
http://lbsbbs.amap.com/forum.php?mod=viewthread&tid=724&highlight=%E5%9D%90%E6%A0%87%E8%BD%AC%E6%8D%A2

**Comment by lilyneaoer** [comment]
`export default async function gps2amap(longitude, latitude) {
  const amapKey = config.http.amapKey;
  const uri = `http://restapi.amap.com/v3/assistant/coordinate/convert?locations=${longitude},${latitude}&coordsys=gps&output=json&key=${amapKey}`;
  const headers = {
    'Content-type': 'application/json; charset=UTF-8',
    Authorization: '',
    method: 'get',
  };
  // 调用高德接口转换坐标
  try {
    const temp = await fetch(uri, headers);
    const data = await temp.json();
    const { locations } = data;
    const tempData = locations.split(',');
    tempData[0] = parseFloat(tempData[0]);
    tempData[1] = parseFloat(tempData[1]);
    return tempData;
  } catch (err) {
    errorInfo(err);
  }
}`

**Comment by lilyneaoer** [comment]
> http://lbsbbs.amap.com/forum.php?mod=viewthread&tid=724&highlight=%E5%9D%90%E6%A0%87%E8%BD%AC%E6%8D%A2

`export default async function gps2amap(longitude, latitude) {
  const amapKey = config.http.amapKey;
  const uri = `http://restapi.amap.com/v3/assistant/coordinate/convert?locations=${longitude},${latitude}&coordsys=gps&output=json&key=${amapKey}`;
  const headers = {
    'Content-type': 'application/json; charset=UTF-8',
    Authorization: '',
    method: 'get',
  };
  // 调用高德接口转换坐标
  try {
    const temp = await fetch(uri, headers);
    const data = await temp.json();
    const { locations } = data;
    const tempData = locations.split(',');
    tempData[0] = parseFloat(tempData[0]);
    tempData[1] = parseFloat(tempData[1]);
    return tempData;
  } catch (err) {
    errorInfo(err);
  }
}`

**Comment by laozhu** [comment]
借楼问下，怎么在 `react-amap` 里面调用 [convertFrom](https://lbs.amap.com/api/javascript-api/guide/transform/convertfrom) 坐标转换方法，我找了半天也没找到，求助。

**Comment by KevenChao** [comment]
> 借楼问下，怎么在 `react-amap` 里面调用 [convertFrom](https://lbs.amap.com/api/javascript-api/guide/transform/convertfrom) 坐标转换方法，我找了半天也没找到，求助。

用 `window.AMap.convertFrom`
