### ISSUE TITLE
如何使用AMap.Geolocation这个插件,实现定位??

### ISSUE THREAD

**Issue by qihui1223** [ElemeFE/react-amap#156]
+ [ ] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [ ] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

**Comment by jim-king-2000** [comment]
可以直接使用GeoLocation API在网页上定位。

**Comment by luofly** [comment]
import Geolocation from 'react-amap-plugin-geolocation';

const pluginProps = {
  enableHighAccuracy: true,
  timeout: 5000,
  showButton: true,
  zoomToAccuracy: false,
  showCircle: true,
  panToLocation: true,
  buttonPosition: 'RB' 
  //, buttonOffset: new window.AMap.Pixel(14, 130)
};

**Comment by luofly** [comment]
< Geolocation 
           ref = {
             (locat) => this.mapLocation = locat
           }
        { ...pluginProps } />

**Comment by luofly** [comment]
可以加我微信danilosun
