### ISSUE TITLE
原生的AMap.Rectangle 对象无法创建，无法创建原生矩形框

### ISSUE THREAD

**Issue by Warden-Thresh** [ElemeFE/react-amap#157]
+ [v ] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [v ] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [v ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### Reproduce Example Link or Code Fragment
this.mapEvents = {
      created(map) {
        console.log(map.getZoom());
        _this.Amap = AMap;
        _this.map = map;
        _this.showCenter();
        var southWest = new AMap.LngLat(116.356449, 39.859008);
        var northEast = new AMap.LngLat(116.417901, 39.893797);

        var bounds = new AMap.Bounds(southWest, northEast);
       //AMap.Rectangle({
        var rectangle = new window.AMap.Rectangle({
          bounds: bounds,
          strokeColor: 'red',
          strokeWeight: 6,
          strokeOpacity: 0.5,
          strokeDasharray: [30, 10],
          // strokeStyle还支持 solid
          strokeStyle: 'dashed',
          fillColor: 'blue',
          fillOpacity: 0.5,
          cursor: 'pointer',
          zIndex: 50,
        });

        rectangle.setMap(map)
        // 缩放地图到合适的视野级别
        map.setFitView([ rectangle ])
      },

#### What is Expected?
希望在地图上画一个矩形框，并且调用editor，但是 
发生如下错误
Unhandled Rejection (TypeError): window.AMap.Rectangle is not a constructor
created
src/pages/DataSetCenter/DataSetMark/index.js:318
  315 | 
  316 | var bounds1 = new AMap.Bounds(southWest, northEast);
  317 | 
> 318 | var rectangle = new window.AMap.Rectangle({
  319 |   bounds: bounds1,
  320 |   strokeColor: 'red',
  321 |   strokeWeight: 6,
目前使用鼠标工具画的矩形框实际上是AMap.Polygon多边形，其editor无法实现矩形的拖动编辑。目前想
使用鼠标工具在地图上做标记，还有编辑以及保存、再此显示到地图上的功能，主要是编辑以及显示已保存编辑需要使用到AMap.Rectangle.
#### What is actually happening?
发生错误 Unhandled Rejection (TypeError): window.AMap.Rectangle is not a constructor
使用了如https://jsfiddle.net/h4u8mdng/14/ 中AMap.plugin('AMap.Geocoder',() => { 的形式，发现Rectangle并不是一个插件，仍旧无法创建矩形对象。
AMap.Geocoder的例子在我的环境中运行良好。

**Comment by Warden-Thresh** [comment]
console.log(AMap.Rectangle); 输出 undefined
console.log(AMap.Polygon) 则有对象输出

**Comment by Warden-Thresh** [comment]
官网例子加载的是v1.4.11,而react-amp加载的是v1.4.0
APILoader中修改如下解决问题
`var DEFAULT_CONFIG = {
  v: '1.4.11',
  hostAndPath: 'webapi.amap.com/maps',
  key: 'f97efc35164149d0c0f299e7a8adb3d2',
  callback: '__amap_init_callback',
  useAMapUI: false
};`

**Comment by ioslh** [comment]
高德官方已强制升级至 V1.4.14
