### ISSUE TITLE
全屏怎么使用

### ISSUE THREAD

**Issue by yahengqi** [ElemeFE/react-amap#159]
+ [ ] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [ ] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

**Comment by jim-king-2000** [comment]
什么叫全屏怎么使用？

**Comment by yahengqi** [comment]
例如:地图默认在屏幕上显示是30%，地图上有个按钮点击之后是100%显示

**Comment by jim-king-2000** [comment]
什么叫“地图默认在屏幕上显示30%”？是不是一开始的时候地图显示在一个小窗口里，单击地图小窗口，就变成了全屏的大地图？

**Comment by yahengqi** [comment]
是你说的这个意思

**Comment by jim-king-2000** [comment]
这个问题跟react-amap库无关。一开始的时候，你可以做一个小的div，把地图放到这个div里。然后为这个div的onclick消息注册一个回调函数。在回调函数里，你可以跳转到一个新页面（新页面就是全屏地图），也可以弹出一个大的（全屏或几乎全屏的）对话框，把map放到这个对话框里即可。

**Comment by yahengqi** [comment]
pc端的全屏和退出全屏，是这样操作的？

**Comment by jim-king-2000** [comment]
基本上，是的。要么用对话框（退出全屏就关闭对话框），要么用新页面（退出全屏就跳回去）。

**Comment by yahengqi** [comment]
地图上全屏按钮需要自己写？自己定位？

**Comment by jim-king-2000** [comment]
全屏按钮需要自己写。定位可能高德地图有。
