### ISSUE TITLE
如何 能 做到路线规划

### ISSUE THREAD

**Issue by ybintian** [ElemeFE/react-amap#16]
需要用到路线规划功能 不知道如何下手

**Comment by ioslh** [comment]
看了下高德官方关于[出行路线规划](http://lbs.amap.com/api/javascript-api/guide/map-data/routeplan#t4) 的说明，都需要使用AMap.service方法加载插件，然后即可在回调中使用路径规划相关功能。

在 react-amap 中集成，可以在 Map 组件的 events.created 事件里进行上述操作，因为这里可以确保高德地图加载成功；然后按照高德接口说明使用相关方法构造和使用实例即可，一个简单的例子比如：https://jsfiddle.net/h4u8mdng/17/
