### ISSUE TITLE
changing default layer

### ISSUE THREAD

**Issue by FGCorp** [ElemeFE/react-amap#161]
+ [ ] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [ ] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### What is actually happening?
i want to use another layer for a foreign contry but i cant figure it out. can you demostrate it with a simple example. thanks all.

**Comment by ioslh** [comment]
amap is only available in China
