### ISSUE TITLE
在移动端的h5不能显示地图

### ISSUE THREAD

**Issue by wz-pro** [ElemeFE/react-amap#164]
#### 创建地图和marker，在本地是好的，部署到服务器后不显示地图
```
render() {
    const { zoomLevel, markerSize, centerLon, centerLat, markerLat, markerLon } = this.props
    const markerStyle = {
      background: 'url(\'http://icons.iconarchive.com/icons/paomedia/small-n-flat/1024/map-marker-icon.png\')',
      backgroundSize: 'contain',
      backgroundRepeat: 'no-repeat',
      backgroundPosition: 'center',
      width: `${markerSize}px`,
      height: `${markerSize}px`,
    }
    return (
      <div style={{ flex: 1 }}>
        <Map
          center={{ latitude: centerLat, longitude: centerLon }}
          zoom={zoomLevel}
          amapkey={this.mapKey}
        >
          <Marker
            position={{ latitude: markerLat, longitude: markerLon }}
          >
            <div style={markerStyle} />
          </Marker>
        </Map>
      </div>
    )
  }
```

#### 报错
Access to XMLHttpRequest at 'http://vdata.amap.com/tiles?mapType=normal&v=2&style=5&rd=2&flds=region,building,road&t=14,13498,6190;14,13500,6190;14,13498,6189;14,13500,6189;14,13499,6190;14,13499,6189&lv=14' from origin '项目的地址' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
/library/map?id=444008#4:1 Access to XMLHttpRequest at 'http://vdata.amap.com/limg?&font=small&scl=2&t=14,13498,6190;14,13500,6190;14,13498,6189;14,13500,6189;14,13499,6190;14,13499,6189&lv=14' from origin '项目的地址' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.

**Comment by weijunext** [comment]
这提示怎么好像是跨域。。。
