### ISSUE TITLE
[建议] 移除文档首页 slogan

### ISSUE THREAD

**Issue by Hybrid-Force** [ElemeFE/react-amap#166]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [x] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### What is actually happening?
https://github.com/ElemeFE/react-amap/blob/de48f215b824f42037f57d10939feb61cbd54ac0/_theme/template/Cover.js#L28-L30

这样的带有政治色彩的 slogan 不利于产品在北美的推广，建议移除。

**Comment by ioslh** [comment]
哈哈哈这个点我没想过，不过北美用不了高德地图

**Comment by Hybrid-Force** [comment]
不管服务在哪里能用或者不能用，产品需要保持政治和文化的中立。请参考ant design的圣诞节彩蛋事件，谨慎行事。
