### ISSUE TITLE
如何通过antd的行政区域联动修改默认的city？

### ISSUE THREAD

**Issue by logyLiang** [ElemeFE/react-amap#17]
因为采用了阿里的dva脚手架，所以状态统一在model内管理了，city变化时候，但地图无变化，应该监听什么事件或者有什么处理方式？由于本人不是专业前端，只是一个后台开发者，描述不清楚的话，见笑了。
![image](https://cloud.githubusercontent.com/assets/22938257/26183267/507e3400-3bb0-11e7-8f87-73344134b802.png)
![image](https://cloud.githubusercontent.com/assets/22938257/26183442/48082af0-3bb1-11e7-98d1-b79180d56e46.png)

**Comment by NoBey** [comment]
你都获取到经纬度了，直接修改 center就行了

**Comment by buxuku** [comment]
请问您解决了这个问题吗？目前我也最到同样的需求，我在地图外部有一个输入框，在输入框中输入详细地址之后，如何把这个地址信息传入Map组件中，来重新通过geocoder.getLocation获取坐标信息之后标注Maker.

**Comment by buxuku** [comment]
我的已经通过`_this.geocoder.getLocation`来解决了。

**Comment by yangmingfa** [comment]
@buxuku  可以分享下吗?我现在的项目也是刚好有这个需求,但是我还没找到解决的办法,求分享解决办法,感谢.

**Comment by buxuku** [comment]
@yangmingfa 
类似于这样的代码
我在input框上面绑定了onChange这个方法。然后通过触发这个方法来调用`geocoder.getLocation`这个方法
PS：组件我用到了antd,里面的message是antd里面的组件。

```javascript
    constructor(props){
        super(props);
        const _this=this;
        this.mapEvents = {
            created(map){
                _this.map = map;
                AMap.plugin('AMap.Geocoder',() => {
                _this.geocoder = new AMap.Geocoder();
                })
            }
        }
    }
    onChange=(event)=> {
        this.getAddressPosition(event.target.value);
    }
    getAddressPosition=(address)=>{
        this.geocoder.getLocation(address, (status, result)=>{
            if (status === 'complete' && result.info === 'OK') {
                if(result.geocodes[0]){
                    const res=result.geocodes[0].location;
                    message.success("定位成功，您也可以继续手动微调");
                    this.setState({
                        position:{
                            longitude: res.lng, latitude: res.lat
                        }
                    })
                }
            }else{
                message.error("自动定位失败，请确认您输入的地址或者手动进行定位");
            }
        });
    }
```

**Comment by yangmingfa** [comment]
@buxuku 明白了,谢谢,我试了,也达到了想要的效果了,感谢感谢

**Comment by cdscawd** [comment]
@buxuku 你好 请问代码中的“AMap” 是如何创建的？我这暂时还没发现方法 谢谢

**Comment by buxuku** [comment]
@cdscawd 你import Map之后，AMap就是一个全局对象了。
