### ISSUE TITLE
为什么引了react-amap后，window下没有挂AMap啊？除了import 'react-amap'，还需要在哪里引入吗？

### ISSUE THREAD

**Issue by greeceGit** [ElemeFE/react-amap#172]
如题。想用一个高德原生组件，然而找不到AMap

**Comment by zhfhz** [comment]
我也是。AMap的官方图层没法手动添加

> 如题。想用一个高德原生组件，然而找不到AMap

**Comment by greeceGit** [comment]
> 我也是。AMap的官方图层没法手动添加
> 
> > 如题。想用一个高德原生组件，然而找不到AMap

**Comment by greeceGit** [comment]
> 直接打印window.AMap就可以看到了，用new window.AMap会有问题。不要依赖编辑器的扩展功能去看window下有没有挂AMap
> 我也是。AMap的官方图层没法手动添加
> 
> > 如题。想用一个高德原生组件，然而找不到AMap

**Comment by greeceGit** [comment]
直接打印window.AMap就可以看到了，用new window.AMap会有问题。不要依赖编辑器的扩展功能去看window下有没有挂AMap
