### ISSUE TITLE
  this.markerEvents = {       created: markerInstance => {         console.log(           '高德地图 Marker 实例创建成功；如果你要亲自对实例进行操作，可以从这里开始。比如：'         );         console.log(markerInstance.getPosition());         const lineArr = [           [116.478935, 39.997761],           [116.478939, 39.997825],           [116.478912, 39.998549],           [116.478998, 39.998555],           [116.478998, 39.998555],           [116.479282, 39.99856],           [116.479658, 39.998528],           [116.480151, 39.998453],           [116.480784, 39.998302],           [116.480784, 39.998302],           [116.481149, 39.998184],           [116.481573, 39.997997],           [116.481863, 39.997846],         ];         // markerInstance.moveAlong([116.478939, 39.997825], 200);       },     };

### ISSUE THREAD

**Issue by liuyunzyj** [ElemeFE/react-amap#178]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [x] 我写了个问题重现的例子，链接或者代码将会贴在下面。

**Comment by liuyunzyj** [comment]
not available   markerInstance.moveAlong([116.478939, 39.997825], 200);

**Comment by liuyunzyj** [comment]
为什么这里其他的高德原生方法都可以调用唯独markerInstance.moveAlong([116.478939, 39.997825], 200);这个调用不了？

**Comment by liuyunzyj** [comment]
官方没有解决的策略吗？

**Comment by ioslh** [comment]
> 官方没有解决的策略吗？

啊抱歉我以为这么久你肯定解决了。原因是你参数传错了。[高德地图文档](https://lbs.amap.com/api/javascript-api/reference/overlay) 说了 `参数path为轨迹路径的经纬度对象的数组`，比如：
```js
const path = [
  [120, 30],
  [110, 30]
].map(([lng, lat]) => new window.AMap.LngLat(lng, lat))
marker.moveAlong(path, 20)
```

**Comment by liuyunzyj** [comment]
解决是解决了，我是直接舍弃了。您这边的这个库。参数错了？我那个时候记得看了类似的参数😂，到时候我在用您这边的库试一试，谢啦------------------ 原始邮件 ------------------
发件人: "ioslh"<notifications@github.com>
发送时间: 2019年7月22日(星期一) 晚上11:44
收件人: "ElemeFE/react-amap"<react-amap@noreply.github.com>;
抄送: "liuyunzyj"<1694382922@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [ElemeFE/react-amap]   this.markerEvents = {       created: markerInstance => {         console.log(           '高德地图 Marker 实例创建成功；如果你要亲自对实例进行操作，可以从这里开始。比如：'         );         console.log(markerInstance.getPosition());         const lineArr = [           [116.478935, 39.997761],           [116.478939, 39.997825],           [116.478912, 39.998549],           [116.478998, 39.998555],           [116.478998, 39.998555],           [116.479282, 39.99856],           [116.479658, 39.998528],           [116.480151, 39.998453], =?UTF-8?Q?__________[116.480784,_39.998302],___________[116.480784,_


 
官方没有解决的策略吗？
  
啊抱歉我以为这么久你肯定解决了。原因是你参数传错了。高德地图文档 说了 参数path为轨迹路径的经纬度对象的数组，比如：
 const path = [   [120, 30],   [110, 30] ].map(([lng, lat]) => new window.AMap.LngLat(lng, lat)) marker.moveAlong(path, 20)
 
&mdash;
