### ISSUE TITLE
如何使用高德地图高级窗体AdvancedInfoWindow？求指教！

### ISSUE THREAD

**Issue by richartan** [ElemeFE/react-amap#18]
现在发现只有基本的infoWindow， 如何加入原生的AdvancedInfoWindow?

**Comment by ioslh** [comment]
参考[这里](https://elemefe.github.io/react-amap/articles/high) ：
> 对于我们尚未提供的组件，你也完全可以在地图的实例创建成功后，亲自调用高德的实例化方法进行创建；一个例子参考[如何使用AMap.Geocoder](https://github.com/ElemeFE/react-amap/issues/12)以及相应的 [jsfiddle](https://jsfiddle.net/h4u8mdng/14/) 示例。 或者在 GitHub 上给我们提交PR或者issue。

**Comment by richartan** [comment]
首先先谢谢快速的回复！我按照你给的示例，写了以下代码，可以调出advancedInfowindow, 但是进行搜索的时候却报错。
![image](https://cloud.githubusercontent.com/assets/6970495/26236211/d5d46eca-3ca1-11e7-8ffb-c52f7c3b23e2.png)
![image](https://cloud.githubusercontent.com/assets/6970495/26236234/f6942a2e-3ca1-11e7-9856-10e30cec6097.png)

**Comment by richartan** [comment]
少了一张错误的screenshot
![image](https://cloud.githubusercontent.com/assets/6970495/26237111/5cecfda6-3ca6-11e7-9ccc-54a31e2e49c7.png)
在jsfiddle上运行也是同样的错误。

**Comment by richartan** [comment]
https://jsfiddle.net/fantasy2005/ko6d187t/

**Comment by ioslh** [comment]
![image](https://cloud.githubusercontent.com/assets/3898898/26237544/2b6b0366-3ca8-11e7-9477-66eaa732664d.png)

注意这一段：
> 如果设置了panel属性，路线规划和poi搜索的结果可以显示在panel指定的div中：[文档地址](http://lbs.amap.com/api/javascript-api/guide/draw-on-map/infowindow)

我看到你设置了 {panel: 'panel'}，页面中应该有个 id 为 panel 的元素才对，否则就会出错。

**Comment by richartan** [comment]
解决了，太感谢了！
附上https://jsfiddle.net/fantasy2005/ko6d187t/ 希望对其他人有帮助。

**Comment by richartan** [comment]
再次感谢@ioslh
