### ISSUE TITLE
TypeScript in react-amap

### ISSUE THREAD

**Issue by sologuy** [ElemeFE/react-amap#182]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [x] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### Reproduce Example Link or Code Fragment

![image](https://user-images.githubusercontent.com/21060714/56214546-acabad00-6090-11e9-88d6-5664d295eb92.png)

#### What is Expected?

新手: 在type script中自定义步行路线规划, 不管是AMap 还是Map对象 无法引用相应的函数,请问怎么破?

**Comment by ioslh** [comment]
`window.AMap`
