### ISSUE TITLE
在created中拿到全局对象AMap后,创建AMap.Geocoder偶尔会报错

### ISSUE THREAD

**Issue by BeautyInNorth** [ElemeFE/react-amap#187]
+ [√ ] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [√ ] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [√ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### Reproduce Example Link or Code Fragment
```
            created: (mapInstance) => {
                const AMap = window.AMap;
                const geocoder = new AMap.Geocoder();
                geocoder.getLocation(this.state.curPosition, (status, result)=>{
                    if (status === 'complete'&&result.geocodes.length) {
                        ...
                    }
                })
            },
```
```
                    <Map
                        amapkey='xxxxxxxxxxxxxxxxx'
                        version='1.4.2&plugin=AMap.Geocoder,AMap.Autocomplete'
                        zoom={13}
                        events={this.amapEvents}
                        center={mapCenter}
                    >
                        <Marker
                            position={curMarker}
                        />
                    </Map>
```
#### What is Expected?
正常创建 `new AMap.Geocoder()`, 使用地理编码服务

#### What is actually happening?
偶尔会出现地图组件created函数执行,在window中拿到AMap后, 使用 `new AMap.Geocoder()` 会出现错误(这时,是能够拿到 AMap的). 我认为应该是异步的问题, 但不知如何解决
![VNX4OP(%TWJ1R46`6%4_P P](https://user-images.githubusercontent.com/40310372/58859805-454bca00-86dd-11e9-9493-6bc9693d3ac1.png)

**Comment by ioslh** [comment]
```js
  AMap.plugin(['AMap. Geocoder'],function(){
      var geocoder = new AMap.Geocoder();
  });
```

**Comment by xu-Aurora** [comment]
> ```js
>   AMap.plugin(['AMap. Geocoder'],function(){
>       var geocoder = new AMap.Geocoder();
>   });
> ```

![image](https://user-images.githubusercontent.com/35291465/130903681-b2cb5c3a-2683-4154-981f-7eaed0e57bb3.png)
按照你的写法了，还是不行，打印不出来东西

**Comment by gggso** [comment]
@xu-Aurora 咋解决的。。
