### ISSUE TITLE
param target value changes in event end  for polyeditor

### ISSUE THREAD

**Issue by superlbr** [ElemeFE/react-amap#189]
+ [√] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [√] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [√] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### Reproduce Example Link or Code Fragment

https://codepen.io/superlbr/pen/rEVrYK?editors=1111

#### What is Expected?

as metioned in [polyeditor](https://elemefe.github.io/react-amap/components/polyeditor),
event 'end' will bring params ```{type,target}```, ```target``` is array in pure html's version 

#### What is actually happening?
target here is a object. and it's key changes by amap's version.
one time, it could be ```["_amap_id", "Kv", "CLASS_NAME", "Kk", "F", "Pg", "ej", "Xa", "Ci", "j3"]```.
Add version="1.4.14" to component ```map```, it will be ```["CLASS_NAME", "lta", "C", "_amap_id", "bG", "Kg", "B", "Ge", "af", "w", "ei", "Qna"]```

**Comment by ioslh** [comment]
The `target` in that context is an amap defined class, details may be changed anytime. **DO NOT** rely on any props beyond [amap documentation](https://lbs.amap.com/api/javascript-api/reference/plugin#AMap.PolyEditor)

**Comment by superlbr** [comment]
as metioned in amap documentation.
```
在调用close方法时，触发该事件，target即为编辑后的折线/多边形对象
```
react-amap work not right, gives unexpected result.
It's difficult to get the real result from `target`

**Comment by ioslh** [comment]
...
