### ISSUE TITLE
plugins, MapType的路况样式

### ISSUE THREAD

**Issue by HaveF** [ElemeFE/react-amap#19]
首先，谢谢这个repo啊！

### react-amap version
0.2.7

### OS/Browers version
macOS/Chrome 58, 60

### 路况的字显示不完全
 [React AMap — 基于 React 的高德地图组件](https://elemefe.github.io/react-amap/components/map)其中第二个例子：
<img width="478" alt="2017-05-21 12 01 15" src="https://cloud.githubusercontent.com/assets/54462/26281065/b224eb9e-3e1d-11e7-82cd-7bb4c852f398.png">

**Comment by ioslh** [comment]
看了一下，这是文档站点的样式问题，有些样式覆盖了高德自己的样式；
感谢提醒，稍后我会改一下。

你自己使用的时候应该不会这样，除非你也不小心写了个样式覆盖了高德的~
