### ISSUE TITLE
关于参数一致性的建议

### ISSUE THREAD

**Issue by HaveF** [ElemeFE/react-amap#20]
hi,

地图中心：
```js
      <Map 
        plugins={['ToolBar']} 
        center={{longitude: 120, latitude: 35}} 
      >
```
但高德官方` [地图显示-地图显示-示例中心-JavaScript API | 高德地图API](http://lbs.amap.com/api/javascript-api/example/map/map-show)`是：

```js
        center: [116.397428, 39.90923]
```

虽然用起来没有问题，但估计有的人还是会有困扰吧....

个人建议仅供参考

**Comment by HaveF** [comment]
这个问题的实际意义在于，用`react-amap`的时候我得对着高德官方文档看例子，所以如果不能运行会有疑惑到底哪不对....

高德官方应该是检查类型，如果是array的话，就转成LngLat?

所以，是不是对array也进行支持会好一些？

**Comment by ioslh** [comment]
有道理，感谢你的建议；下一次升级我也会支持 array 配置坐标。

**Comment by tongliwei123** [comment]
请问 我该如何在点击Maker的同时调用起高德客户端呢

**Comment by HaveF** [comment]
@tongliwei123 你仔细看一下文档，设置下makrs的click events就可以了

**Comment by tongliwei123** [comment]
您能给发个例子么？确实有点着急用

发件人: HaveF
答复: ElemeFE/react-amap
日期: 2017年5月26日 星期五 上午2:17
至: ElemeFE/react-amap
抄送: wuhuihui, Mention
主题: Re: [ElemeFE/react-amap] 关于参数一致性的建议 (#20)


@tongliwei123<https://github.com/tongliwei123> 你仔细看一下文档，设置下makrs的click events就可以了

**Comment by HaveF** [comment]
不能。
