### ISSUE TITLE
plugin 的 toolbar 似乎有点问题

### ISSUE THREAD

**Issue by HaveF** [ElemeFE/react-amap#21]
### react-amap version
0.2.7

在 [Edit fiddle - JSFiddle](https://jsfiddle.net/urncdtdf/)只加了
```js
         AMap.plugin('AMap.ToolBar',() => {
          var tool = new AMap.ToolBar(); 
          _this.map.addControl(tool);
          _this.toolbar = tool;
         })
```
![2017-05-22 7 34 00](https://cloud.githubusercontent.com/assets/54462/26306364/aaa79570-3f25-11e7-9cb3-70d5f8141498.png)
显示的是没有问题的。

但是在自己的工程中，就有点问题了
```js
      {
        name   : 'ToolBar',
        options: {
          visible : true,  // 不设置该属性默认就是 true
          ruler   : true,
          onCreated(ins){
            //console.log(ins);
          },
        },
      }
```
ruler显示不出来（而且应该默认就是true），用onCreated把toolbar取出来，然后做类似
`    this.mapToolbar.showRuler()`
仍然显示不了。
见其中第二个图： [React AMap — 基于 React 的高德地图组件](https://elemefe.github.io/react-amap/components/map)
![2017-05-22 7 37 51](https://cloud.githubusercontent.com/assets/54462/26307264/4787808a-3f26-11e7-89f6-7b7b25ee6a43.png)

另外，toolbar的默认位置变成了右下，也不是官方的左上。

jsfiddle上的react-amap是0.2.6版本，和这个有关系吗？

**Comment by ioslh** [comment]
你好，这个跟版本没关系。查看[高德官网关于 ToolBar 的可配置项](http://lbs.amap.com/api/javascript-api/reference/map-control#AMap.ToolBar)，有一个`liteStyle`属性，表示简洁模式；官方的 API 默认为 `false`，我觉得简洁模式比较好看，在封装时默认设置成了` true`；还有位置的不一致也是因为我修改了`position` 默认值。

如果你需要高德官网的那个形式，可以重新配置这两个属性，参考示例：https://jsfiddle.net/h4u8mdng/18/

**Comment by HaveF** [comment]
谢谢啊。原来是这样。
那就建议在 [React AMap — 基于 React 的高德地图组件](https://elemefe.github.io/react-amap/components/map)的plugin处提一嗓子。我说怎么回事呢。

另外，position的默认值个人建议还是左上比较好，因为如果是右下的话，那个overview / 鹰眼打开后会和toolbar重合。当然，还是以你的喜好为准。

**Comment by yolo-ling** [comment]
尴尬啦,同样问题
