### ISSUE TITLE
怎么使用AMap.DistrictSearch这个构造方法

### ISSUE THREAD

**Issue by hellobinbin** [ElemeFE/react-amap#23]
### react-amap version

怎么调用搜索功能，我搜索了整个项目都找到AMap.DistrictSearch这个api

**Comment by ioslh** [comment]
你好，react-amap 并没有对这个组件进行封装；
高德的组件文档在这里 http://lbs.amap.com/api/javascript-api/guide/map-data/cministrative_division/；

**Comment by hellobinbin** [comment]
怪不得找了半天没找到，所以改用百度了。3q

**Comment by sunnyabc789** [comment]
如果是绘制地区区域,可以启用amapUI,希望能帮助后来的人

**Comment by sunnyabc789** [comment]
如果是绘制地区区域,可以启用amapUI,希望能帮助后来的人
if your request is draw area, you can use amapUI to solve

**Comment by tylerrrkd** [comment]
@sunnyabc789 ohh, nice guy.
