### ISSUE TITLE
请问此高德react api支持高德插件吗？

### ISSUE THREAD

**Issue by fufjvnvnf** [ElemeFE/react-amap#25]
### react-amap version
0.2.7

### OS/Browers version
macOS/Safari

### Reproduction Link
无

### What is actually happening?
如题 请问如果想加入这里的例子所示的https://lbs.amap.com/api/javascript-api/reference/plugin heapmap插件，如题如何调试？谢谢

**Comment by ioslh** [comment]
hi~ 之前一直没有很好的思路来解决内置组件供不应求的问题，你现在可以通过扩展自定义组件来试试啦； https://elemefe.github.io/react-amap/articles/extend

**Comment by ioslh** [comment]
关于调试，难道不是修改……然后刷新看效果嘛……嘿嘿
