### ISSUE TITLE
是否有计划支持UI组件库

### ISSUE THREAD

**Issue by e1emeb0t** [ElemeFE/react-amap#26]
```js
const plugins = ['Scale', 'ToolBar'];
const components = ['SvgMarker'];
/* ... */
<Map plugins={plugins} components={components} />
```

http://lbs.amap.com/api/javascript-api/guide/amap-ui/intro

**Comment by ioslh** [comment]
你好，之前是没有这方面的计划的。

不过我了解了一下高德 UI 组件库，好几个都是对原有的组件的加强（如敷盖物，信息窗体），我不准备支持增强的 UI，因为 react-amap 中封装的 Marker 和 InfoWindow 组件可以很方便写出丰富样式的 HTML （JSX 语法）来定制外观。针对 标注列表组件，react-amap   已经有组件（Markers）用于渲染批量标注点；

下一步的技术是支持城市选择器组件，POI选点组件。

**Comment by fufjvnvnf** [comment]
谢谢！请问会考虑支持热力图吗？

**Comment by e1emeb0t** [comment]
多谢, 那我还是用高德原生API来实现吧
