### ISSUE TITLE
bisheng 使用疑问

### ISSUE THREAD

**Issue by jindada** [ElemeFE/react-amap#28]
您好 我正在用您的代码学习bisheng 有个问题想请教您

![image](https://user-images.githubusercontent.com/16317349/27276374-9cf4cb02-550d-11e7-8b1e-31895baadb2e.png)

这个里面的 highlightedCode 和 preview 是如何注入到 pageData 中的啊？查阅了相关文档和代码都没有找到相关的内容

bisheng版本：0.24.1

谢谢

**Comment by ioslh** [comment]
在插件 `bisheng-plugin-antd` （0.3.2）里；

```
// lib/process-demo.js
  markdownData.highlightedCode = getHighlightedCode(contentChildren, codeIndex);
  markdownData.preview = getPreview(contentChildren, codeIndex);
```

这个插件应该是专门为了 antd 项目写的；我的也是用这个插件，所以采用了一样的目录结构。

**Comment by jindada** [comment]
我已经在配置了 bisheng-plugin-antd  版本 0.15.0
![image](https://user-images.githubusercontent.com/16317349/27277873-4fe84ba4-5512-11e7-9cb5-0b3ffe0e566c.png)

但是在哪里可以获取到 这两个方法那？
@ioslh 谢谢

**Comment by ioslh** [comment]
不是 `lib/process-demo.js` 里吗？不是的话你直接在插件源代码里搜一下关键字

**Comment by jindada** [comment]
确实是在的 但是bisheng的插件不可以直接注入到props里面去吗 我看antd和react-amap都是配置plugins就可以用啦

**Comment by ioslh** [comment]
这个插件应该是专门为了 antd 项目写的，你得用 antd 项目一样的目录结构。
