### ISSUE TITLE
点聚合问题

### ISSUE THREAD

**Issue by lanxxg** [ElemeFE/react-amap#29]
请问，组件`Markers`  可以在点击聚合点时不弹窗，而是显示其下级Marker吗？谢谢

**Comment by ioslh** [comment]
「显示其下级Marker」，以什么形式显示？现有设计就是点击聚合点时，在弹窗中显示其下级Marker。

**Comment by lanxxg** [comment]
不好意思没表述清楚，点击聚合点时，对地图进行缩放，直接在地图上显示下级`Marker`  不弹窗显示。

**Comment by ioslh** [comment]
我明白了。这是高德地图对聚合点的默认行为。react-amap 内置的 Markers 组件我不准备改了；我在考虑以插件的形式重写 Markers 组件（单独的 npm 库），类似于[react-amap-plugin-heatmap](https://www.npmjs.com/package/react-amap-plugin-heatmap) 。

不过最近一周可能没时间；如果你有兴趣或者比较紧急你可以尝试自己写一个 Markers 组件，参考文档 [自定义地图组件](https://elemefe.github.io/react-amap/articles/extend)。

**Comment by lanxxg** [comment]
好的，了解。
