### ISSUE TITLE
[DOC] CDN 地址不存在

### ISSUE THREAD

**Issue by AxeMea** [ElemeFE/react-amap#3]
### CDN 地址不存在

```javascript
https://unpkg.com/react-amap@VERSION/dist/react-amap.js
https://unpkg.com/react-amap@VERSION/dist/react-amap.min.js
```

来源：https://elemefe.github.io/react-amap/articles/start

**Comment by YongX** [comment]
他这里应该是想说 `VERSION` 是个占位符，填上自己想要的版本号。不过加上一些说明文字应该会更加清晰点

**Comment by AxeMea** [comment]
有点复杂了，直接把最新的版本 `cdn` 地址放到文档上就好了。新用的用户一般不会关心版本，除非有特殊版本。

如果文档只告诉用户规则，用户还得找到最新版本，再自己拼出来 `url` 来引用 `CDN` 这不太合理。

**Comment by ioslh** [comment]
@AxeMea @YongX 文档已更新~https://elemefe.github.io/react-amap/articles/start
