### ISSUE TITLE
请问如何加载插件？

### ISSUE THREAD

**Issue by toutouli** [ElemeFE/react-amap#30]
你好，我打算实现地理编码的功能，看高德的文档，说是要引入AMap.Geocoder插件。请问一下，有没有引入插件的方法？

**Comment by ioslh** [comment]
参考这里： #12 ，
或者这里：[自定义地图组件](https://elemefe.github.io/react-amap/articles/extend)

**Comment by toutouli** [comment]
你的回答已经解决了我的疑惑，谢谢，建议完善文档created事件的详细使用方法，我当时看完文档里created的示例后完全略过了。不过有可能是我自身水平不足的原因。冒昧了。

**Comment by ioslh** [comment]
好的，谢谢你
