### ISSUE TITLE
可以调用AMapUI的API吗?

### ISSUE THREAD

**Issue by sumlight** [ElemeFE/react-amap#33]
### react-amap version
1.0.1

### OS/Browers version
macOS/Chrome 59

AMap有一些UI组件, 如http://lbs.amap.com/api/javascript-api/example/amap-ui-poipicker/index,
react-amap里可以调用这些API吗? 我看了自定义组件, 还是不知道怎么用AMapUI

**Comment by ioslh** [comment]
目前是没有，不过已经碰到好几个人提到这个需求，我准备把这个集成到 Map 组件中。

**Comment by sumlight** [comment]
great! thanks : )

**Comment by zhengqingxin** [comment]
请问现在有这个功能了吗？
