### ISSUE TITLE
有没有导航插件

### ISSUE THREAD

**Issue by li5570598** [ElemeFE/react-amap#34]
有没有导航功能啊，比如传入起始坐标，终点坐标，交通方式等参数后，生成路线？

**Comment by li5570598** [comment]
高德地图官方文档中有一个setFitView方法，如何在Map组件中调用呢？

**Comment by ioslh** [comment]
没有导航功能。

在 Map 组件的 [created 事件](https://elemefe.github.io/react-amap/components/map#events-配置) 中获取 map 实例的引用并保存，然后可以在需要的时候调用 `map.setFitView`。

**Comment by li5570598** [comment]
确实是这样，实在是太感谢了。

**Comment by li5570598** [comment]
以后会不会增加新模块呢，比如导航？
