### ISSUE TITLE
events很好用。但有没有解绑事件呢？

### ISSUE THREAD

**Issue by cw19931024** [ElemeFE/react-amap#36]
貌似高德自带的解绑好像没用

**Comment by YongX** [comment]
解绑的场景是啥？为了重新绑新的么

**Comment by ioslh** [comment]
要解绑也并不是办不到的，当前你可以按照这个 [JSFIDDLE](https://jsfiddle.net/mxc0h16p/11/) 所示的方式进行解绑：

1. 保存好绑定的函数的引用；
2. 保存事件绑定的对象实例（如上例中的 `this.map`）；
3. 在需要解绑的时候直接使用 `off` 方法。

不过还是想了解一下解绑的场景？因为我觉得单纯是为了不让事件触发的话，可以设置一个 flag 变量，在事件回调内部判断这个 flag，需要解绑的时候改变 flag 就可以了。

**Comment by cw19931024** [comment]
对的，虽然对于解绑这个可以利用一个flag来判断，但是如果在复杂的逻辑情况下，维护起来会很臃肿不堪。当然有的话我觉得会更好。

**Comment by liuzhen88** [comment]
@cw19931024 如何添加点击事件的？

**Comment by cw19931024** [comment]
@liuzhen88 
有自带参数events
![image](https://user-images.githubusercontent.com/15888370/30469375-8779e87a-9a22-11e7-9eef-985e37fac39c.png)
![image](https://user-images.githubusercontent.com/15888370/30469390-a3af3da6-9a22-11e7-8f2e-ee8445a6b047.png)
文档有很好的例子的

**Comment by liuzhen88** [comment]
@cw19931024 谢谢你
