### ISSUE TITLE
Polyline 组件数组 重绘时未完全清除上一次绘制的线条

### ISSUE THREAD

**Issue by crcrcry** [ElemeFE/react-amap#38]
### react-amap version
- react-amap 1.0.2

### OS/Browers version
- macOS Sierra 10.12.5
- Chrome 版本 60.0.3112.90（正式版本） （64 位） 

### Reproduction Link

- 因为一些原因不方便贴链接，直接放代码和截图好了

### Steps to reproduce
- 同上

### Code
```js
export default class MapArea extends Component {
  constructor(){
    super();

    this.mapPlugins = ['ToolBar'];
    this.mapEvents = {
      click: (e) => {
        this.props.changePosition(e.lnglat);
      }
    }
  }

  render(){
    const polylineArr = this.props.roads.map((item, index) => {
      return(
        <Polyline
          key={`polyline${index}`}
          path={[{
              longitude:item.coordinates[0][0],
              latitude: item.coordinates[0][1],
            }, {
              longitude:item.coordinates[1][0],
              latitude: item.coordinates[1][1],
            }]}
          style={{strokeColor: '#f00', strokeOpacity: 0.5+0.5*Number.parseFloat(item.probability), strokeWeight: 7}}
        />
      )
    });

    return (
      <div>
        <div style={style.mapArea}>
          <Map plugins={this.mapPlugins} center={this.props.position} events={this.mapEvents} zoom={17}>
            <Marker
              position={this.props.position}
            />
            {polylineArr}
          </Map>
        </div>
      </div>
    )
  }
}
```

### What is Expected?
- 一个 react-amap，在上面画一些线条
- 上一轮查询 this.props.roads.length = 16，画出 16 条线
- 本轮查询 this.props.roads.length = 1，画出 1 条线，同时清除掉上一轮的 16 条线。

### What is actually happening?
- 上一轮的 16 条线只有第 1 条被清除且重绘了，其他 15 条没有被清除，仍在地图上。

#### 上一轮查询，ui + 控制台
<img width="1680" alt="2017-08-13 4 24 50" src="https://user-images.githubusercontent.com/19330440/29248171-13f0367c-8044-11e7-96f7-f8013da3f7db.png">

#### 本轮查询，ui + 控制台
<img width="1680" alt="2017-08-13 4 25 10" src="https://user-images.githubusercontent.com/19330440/29248172-1d185c34-8044-11e7-96e1-425dd11f4479.png">

**Comment by crcrcry** [comment]
多测试了几次发现：如果新的 polyline 数组没有老的数组长，那老的数组长出来的那部分线条则不会重绘，仍然留在地图上。

**Comment by ioslh** [comment]
很抱歉，确实是个 bug，今天会发个新版本修复这个问题。

**Comment by ioslh** [comment]
你好，更新 1.0.3 版本修复了[这个问题](https://github.com/ElemeFE/react-amap/commit/ac2c676d6f035a316c3d70139a9be1beeee30526)。

**Comment by crcrcry** [comment]
非常感谢，饿了么大前端很赞
