### ISSUE TITLE
如何在map或者market事件外调用它们的方法呢？

### ISSUE THREAD

**Issue by cw19931024** [ElemeFE/react-amap#39]
`
import Map from 'react-amap'

this.state={
events:{
zoomchange: function (target) {
            console.log(this.getZoom())
            this.getZoom()
          },
     }
}

test=()=>{
//这里如何调用map,market的方法？
}

<Map events={this.state.events} />
`

**Comment by ioslh** [comment]
把实例保存到外部变量里
