### ISSUE TITLE
AMap.CloudDataLayer 如何使用？

### ISSUE THREAD

**Issue by VanquisherMe** [ElemeFE/react-amap#45]
### react-amap version
1.0.3 

> 请教一下 AMap.CloudDataLayer 现在有方案能够使用么 ，浏览到#23
主要问题是 不知道在哪可以得到 AMap

**Comment by ioslh** [comment]
`window.AMap` 应该就可以吧？

**Comment by VanquisherMe** [comment]
![image](https://user-images.githubusercontent.com/4927398/30946879-07d256b8-a439-11e7-8649-acd15c340532.png)

> 希望能给一些思路，尝试没有调用到

![image](https://user-images.githubusercontent.com/4927398/30946924-50e76924-a439-11e7-97da-01b9442e664d.png)
![image](https://user-images.githubusercontent.com/4927398/30946934-5b7b33ac-a439-11e7-85e9-be1cead6b4c4.png)

> cloudDataLayer返回的数据格式好像并不一样，是重构了么

**Comment by ioslh** [comment]
数据格式不一样是因为接入的高德 SDK 的版本不一样，`react-amap` 目前是 1.3，高德官方示例已经更新到了 1.4.0。`react-amap` 正在适配新版（1.4.0）进行修改。

**Comment by ioslh** [comment]
我试了下发现也没起作用😓

**Comment by ioslh** [comment]
试了可以使用的。使用的 key 跟 tableid 要对应。1.3 版本和 1.4.0 版本的高德接口都是可以使用的。

https://jsfiddle.net/mxc0h16p/13/

**Comment by VanquisherMe** [comment]
感谢您的解答！
