### ISSUE TITLE
使用react-map显示无法找到文件

### ISSUE THREAD

**Issue by lijingcsu** [ElemeFE/react-amap#46]
react-amap version 1.0.3 
OS/Browers version centos 7.4  版本 61.0.3163.100（正式版本） （64 位）
使用例子如下：
import { Map } from 'react-amap';
import React from 'react';
class ReactAmapShow extends React.Component{
    render(){
        return <div style={{width: '100%', height: '400px'}}>
            <Map amapkey={'22fd6e60f6b3ca19cd2dd588b167647e'}/>
        </div>
    }
}

export default ReactAmapShow;
在浏览器中打开，报错如下：
bundle.js:123738 GET file://webapi.amap.com/maps?v=1.3&key=******&callback=__amap_init_callback net::ERR_FILE_NOT_FOUND
在谷歌上搜索了一下，是需要自己引入高德的js文件吗？

**Comment by lijingcsu** [comment]
index.html#/cd/deploy/process:1 Uncaught (in promise) Event {isTrusted: true, type: "error", target: script, currentTarget: null, eventPhase: 0, …}

**Comment by ioslh** [comment]
在本地部署一个 HTTP 服务器，通过服务器打开你的页面。
