### ISSUE TITLE
【建议】删掉库中定义的地图内层div背景色

### ISSUE THREAD

**Issue by babycannotsay** [ElemeFE/react-amap#48]
【使用场景】使用高德的自定义地图时，即`mapStyle`属性设置为类似`amap://styles/9104b475b707060c9a89f69e10db86f4`的值。如果地图背景颜色与库中定义的内层div背景色相差过大，会有一种闪的很明显的感觉。

【建议】建议将库中设置的背景色删除，或者设置为`transparent`。让用户设置背景颜色。类似

    <div style={{backgroundColor: 'orange'}}>
      <Map></Map>
    </div>

也可以给Map自定一个背景颜色属性。

【位置】库中使用的地图内层div背景色是#eee, 位置在react-amap->lib->map->index.js 452:71

**Comment by babycannotsay** [comment]
这个[demo](https://jsfiddle.net/ioslh/mxc0h16p/8/) 中，给`<Map />`加` amapkey="c498e5baa2f939771e5a07e6d4f5643f"
        mapStyle="amap://styles/9104b475b707060c9a89f69e10db86f4"`,
然后拖动地图，可以感觉出来。

**Comment by ioslh** [comment]
好。感谢~

**Comment by ioslh** [comment]
已升级 [v1.1.0](https://elemefe.github.io/react-amap/articles/upgrade)，欢迎使用。
文档目前不完整，这几天补充。
