### ISSUE TITLE
PropTypes

### ISSUE THREAD

**Issue by andrevenancio** [ElemeFE/react-amap#51]
Several of the dependencies for this project are outdated, making this module annoying to use for React 15+ versions.

From what I can detect this are the modules:

`react-router` *imported:* `3.0.2` *latest:* `4.2.0`
`isomorphic-style-loader version` *imported:* `1.1.0` *latest:* `4.0.0` 

should use PropTypes from 'prop-types' and not from 'react' package.

**Comment by andrevenancio** [comment]
hey, did this version get updated on npmjs? I've pulled the latest from npmjs and still have this error happening

**Comment by joshua7v** [comment]
@andrevenancio nope, its still 1.1.3, you have to wait for newer release. 
I'm not sure what error did you get, but you can use `npm i @joshua7v/react-amap` temporarily to git rid of warnings of propTypes if it does matters.

**Comment by andrevenancio** [comment]
yeah. good idea. I'll pull directly from your repo. Keep this updated when its merged to npm though?
thanks

**Comment by ioslh** [comment]
um 1.1.4 was released just now
