### ISSUE TITLE
使用Marker、Polygon组件之后，要实现对于针对指定覆盖物的setFitView,有何良策？

### ISSUE THREAD

**Issue by margox** [ElemeFE/react-amap#52]
比如有个功能点是以最合适的缩放级别和位置来显示地图上的一组Marker，
使用原始的高德API，我们可以这样做：
```
const markers = coordinates.map(position => new Marker({ map, position }))
const showAllMarkers = () => {
  map.setFitView(markers)
}
```
使用React-AMap之后，要实现这种需求有什么好办法么？

**Comment by ioslh** [comment]
暂时还没有想到怎么以 React 那样声明式的方式来做这个行为。

目前来说，只能在覆盖物实例创建好之后再手动调用原生方法，如这个 https://jsfiddle.net/mxc0h16p/16/ 所示。

**Comment by margox** [comment]
看来只能酱紫啦，基于组件属性来做这种类型的功能也确实没什么好办法🤓🙄🤔

**Comment by jim-king-2000** [comment]
@ioslh 你的demo里面，如果markers都不动，则没问题。如果markers会动，动了之后要重新setFitView，那该怎么办？

**Comment by Symous** [comment]
@ioslh 谢谢，老哥。

**Comment by ZHENGGEGE** [comment]
@ioslh  这样写了以后 如果标记有浮窗，点击标记显示浮窗，弹出来浮窗地图位置会移动一下，但是这个setFitView方法会把显示浮窗时候移动的位置又移动回来
