### ISSUE TITLE
请问 用这个组件是否可以 自定义UI图层 切换啊  

### ISSUE THREAD

**Issue by America-first-melon** [ElemeFE/react-amap#53]
### Steps to reproduce
好像说是没有支持 AMapUI

**Comment by ioslh** [comment]
你是说这个[图层](http://lbs.amap.com/api/javascript-api/reference/layer)功能吗？

**Comment by America-first-melon** [comment]
@ioslh  是的   我想套一层自己的地图UI层  不知道可不可行  看之前的issues 好像是没支持。

**Comment by ioslh** [comment]
可以自己写一个自定义图层组件；参考[这个示例](https://jsfiddle.net/mxc0h16p/17/)中的 `MyTile`  组件实现方式。

关于自定义图层可以参考[如何写一个自定义的地图组件](https://elemefe.github.io/react-amap/articles/extend)，希望可以帮到你

**Comment by ioslh** [comment]
修改了一下例子，https://jsfiddle.net/mxc0h16p/19/

**Comment by America-first-melon** [comment]
o  这个是图片图层啊  我试试   谢谢
