### ISSUE TITLE
请问我应该如何使用AMap.Driving，麻烦给我个示例可以吗？多谢了！

### ISSUE THREAD

**Issue by tz198849** [ElemeFE/react-amap#54]
官方提供的示例都打不开了。。。

> 一个例子参考如何使用AMap.Geocoder以及相应的 jsfiddle 示例    这里的示例打不开

**Comment by tz198849** [comment]
请问有人吗？我如何使用 react-amap 里面没有的组件啊。给予 react-amap 我试了好多方法。在__map__中都获取不到啊。。。

**Comment by ioslh** [comment]
哪个示例打不开？链接贴一下吧。

**Comment by ioslh** [comment]
贴一下你尝试过的代码。

**Comment by tz198849** [comment]
https://jsfiddle.net/h4u8mdng/14/   由于我是liunx 系统。没有翻墙工具，所以这个地址打不开，我用mac翻墙后打开了，我成功按照您的方法找到了 高德的 AMap.Driving ，但是我进一步实现的时候。找不到 它的 search调用 ，不知道您能否为我演示下 使用 react-amap 来使用下 AMap.Driving 插件。非常感谢您的回答。您可以继续在 上面的网站进行示例，我会用翻墙电脑打开。再次感谢。
这是我想要实现的效果：
http://lbs.amap.com/api/javascript-api/guide/map-data/routeplan#t5

**Comment by ioslh** [comment]
https://jsfiddle.net/mxc0h16p/20/

**Comment by tz198849** [comment]
非常感谢，已经解决。我忘记添加一个div 带上id了。。。真是悲剧。。。谢谢
