### ISSUE TITLE
如何给地图绑定多边形事件？

### ISSUE THREAD

**Issue by loycoder** [ElemeFE/react-amap#56]
如何绑定draw事件，实现绘多边形 呢？原生JS 是这样过写的：
![image](https://user-images.githubusercontent.com/33513180/32988362-d3da567a-cd3d-11e7-909e-c4781f965709.png)。

**Comment by ioslh** [comment]
可以参考一下这个 [MouseTool 组件](https://elemefe.github.io/react-amap/components/mousetool)。
