### ISSUE TITLE
请问如何调用高德官方的 MarkerClusterer插件自定义聚合坐标样式？

### ISSUE THREAD

**Issue by Wphilipp** [ElemeFE/react-amap#57]
react-amap 的plugins提供的5种插件没有markClusterer，还有其他方法调用高德的这个插件吗，试过直接调用高德的api，但是如何获取高德的AMap对象？通过 events.created获取的是实例。
### react-amap version

v1.1.2
### OS/Browers version

chrome 53

**Comment by ioslh** [comment]
你好，react-amap 的 Markers 组件已经可以配置使用 AMap.MarkerClusterer 插件了 ，参考[useCluster 属性的使用](https://elemefe.github.io/react-amap/components/markers)。
另外能否简要描述一下你想使用 AMap.MarkerClusterer 实现的需求，我收集一下需求好做进一步开发。

获取高德的AMap对象直接 `window.AMap` 就可以了。

**Comment by Wphilipp** [comment]
通过useCluseter好像只能使用默认样式的Clusterer，我需要自定义样式，所以尝试如下写法，但是控制台提示没有该插件
`const plugins = [
      {
        name: 'MarkerClusterer',
        options: {
          map: this.mapInstance,
          markers: this.markerInstance,
          opts: {
            gridSize: 50,
            renderCluserMarker:this._renderCluserMarker
          }
        }
      }
    ]`
场景需求是 在地图上展示各个地区物联网设备的运行状态，不同故障级别的设备对应用不同的颜色的mark表示，一个地区的clusterer颜色由该地区内故障级别最高的mark的颜色表示。

**Comment by ioslh** [comment]
useCluster 支持传入对象配置，参考这个示例 https://jsfiddle.net/y9cv20cv/10/ 的使用。

不过你提醒了我， Markers 组件的设计不够灵活，覆盖了 Clusterer 默认的点击行为。近期会稍微升级一下以插件形式提供。

**Comment by Wphilipp** [comment]
OK 谢谢大佬

**Comment by Wphilipp** [comment]
在问一下 如何获取这个mark对象？
[https://jsfiddle.net/y9cv20cv/11/](url)

**Comment by ioslh** [comment]
绑定 events.created 方法。参考 [Markers 组件](https://elemefe.github.io/react-amap/components/markers)的 **事件绑定** 示例

**Comment by Wphilipp** [comment]
好的，谢谢

**Comment by zuiidea** [comment]
@ioslh   https://jsfiddle.net/y9cv20cv/10/  这个例子无法打开了，useCluster 支持传入对象配置能否在文档中体现

**Comment by zuiidea** [comment]
useCluster 使用 `MarkerClustererOptions`，renderClusterMarker 属性无效，可以参考这个在线例子

https://codesandbox.io/s/gaode-q6j8c
