### ISSUE TITLE
无法使用features参数？

### ISSUE THREAD

**Issue by Leo2088** [ElemeFE/react-amap#58]
在官方文档 https://elemefe.github.io/react-amap/components/map 我看到有 features 参数介绍，但在index.d.ts文件中却没看到这个参数校验？目前无法在项目中正常使用 features。

features
设置地图上显示的元素种类。支持'bg'（地图背景）、'point'（POI点）、'road'（道路）、'building'（建筑物）

**Comment by ioslh** [comment]
很抱歉，遗漏了。
已经更新 1.1.3 版本补上了。欢迎反馈~

**Comment by Leo2088** [comment]
好的，非常感谢。
