### ISSUE TITLE
 标签上用 features 数组，每次 render 都会闪。

### ISSUE THREAD

**Issue by jljsj33** [ElemeFE/react-amap#59]
https://github.com/ElemeFE/react-amap/blob/master/components/map/index.js#L259

踩了个坑, 这判断对 render 里写在标签上的 object / array  无效。每次 render 都是个新对象了。。

```jsx
<Map features={[ 'bg', 'road', 'building' ]} />
```

这样写每次 render 都会闪一下。。

建议写个提醒， 如:

```jsx
const features = [ 'bg', 'road', 'building' ];
...
render(){
  return (<Map features={features} />);
}
...
```

或用社区的这方面的类判断下, [deep-eql](https://www.npmjs.com/package/deep-eql)；

**Comment by ioslh** [comment]
你说的提醒，其实在[这里](https://elemefe.github.io/react-amap/articles/practice)。
不过你说的  deep-eql 这个方案似乎更好，我去了解一下，感谢反馈~

**Comment by jljsj33** [comment]
好吧，没注意有这个。。。
