### ISSUE TITLE
AMapUI 组件库无法引入ui/misc/PathSimplifier

### ISSUE THREAD

**Issue by unionTime** [ElemeFE/react-amap#60]
react-amap 版本为^1.1.3

代码：
```
window.AMapUI.loadUI(['ui/misc/PathSimplifier'], function(PathSimplifier) {
        
            if (!PathSimplifier.supportCanvas) {
                alert('当前环境不支持 Canvas！');
                return;
            }
            console.log(PathSimplifier);
            //启动页面
            initPage(PathSimplifier);
    })
```
准备引入轨迹组件，报错：
<img width="796" alt="a935c002-5cc4-4e5e-b21b-dbef5d7d55e2" src="https://user-images.githubusercontent.com/19386499/33228230-1da03ac4-d1f1-11e7-8130-8b57f1fbc518.png">

在引入其他组件如 overlay/SimpleMarker 时没有报错！

请问如何解决呢？

**Comment by unionTime** [comment]
已经找到错误了，原生官网上AMapUI是要引入ui/misc/PathSimplifier。而react-amap已经为我们添加了 ui/。 因此，改为引入misc/PathSimplifier就成功了。打扰了～

**Comment by ioslh** [comment]
其实真相在这里哦

http://lbs.amap.com/api/javascript-api/reference-amap-ui/mass-data/pathsimplifier
![image](https://user-images.githubusercontent.com/3898898/33231953-d4b87a18-d238-11e7-8750-01f19ee20ee8.png)

**Comment by jutian88** [comment]
@ioslh @unionTime 请问下, react如何导入原生AMapUI呀,正是因为react, 才选择npm react-amap的! 但不支持pathsimplifier

**Comment by ioslh** [comment]
[文档](https://elemefe.github.io/react-amap/components/map) 这里有介绍加载 AMapUI 组件库的方法。
