### ISSUE TITLE
markers组件，无法更新markers

### ISSUE THREAD

**Issue by beeant0512** [ElemeFE/react-amap#63]

**Comment by ioslh** [comment]
能提供一个重现示例吗？

**Comment by qilovehua** [comment]
`
<Map amapkey={Config.AMAP_KEY} center={center} zoom={zoom}>
              <Geolocation enableHighAccuracy={true} timeout={10000} events={this.geoEvents} />
              <Markers markers={makers}
                      events={this.makerEvents}
                      render={this.renderMarkerLayout} />
              <Marker position={center} />
</Map>
`
makers只有一个，渲染后跟center重叠了，两个还是有点距离的。
更新center，makers不变，makers的位置会出现在上次center的位置，每次更新center都这样。
有时更新后上次makers没消失。

center,zoom,makers都是在redux里的，页面setState也一样。
 版本1.1.3  @ioslh

**Comment by qilovehua** [comment]
<Map amapkey={Config.AMAP_KEY} center={center || { longitude: 121.48, latitude: 31.22 }} zoom={zoom}>
              <Geolocation enableHighAccuracy={true} timeout={10000} events={this.geoEvents} />
              
              <Markers markers={makers}
                      events={this.makerEvents}
                      render={this.renderMarkerLayout} />
              <Marker position={center} />
</Map>

**Comment by ioslh** [comment]
我写了个[示例](https://jsfiddle.net/ioslh/y9cv20cv/16/)，还是没法重现。

你看看是不是跟你使用代码逻辑一样？或者在我那个示例基础上修改一下重现这个 bug

@qilovehua @beeant0512

**Comment by qilovehua** [comment]
@ioslh 我用魅蓝X android 6.0测的，手机自带浏览器，一切都很正常，如果是在微信公众号里访问的话，出现问题的概率比较大。
iphone6p，开启定位，很多时候获取不到位置，用的是react-amap-plugin-geolocation

**Comment by zhanglingsi1** [comment]
markers不全量更新，更新其中单个或多个，没生效 https://jsfiddle.net/y9cv20cv/292/ @ioslh
