### ISSUE TITLE
逆向地理编码的Geocoder函数怎么调用呢？

### ISSUE THREAD

**Issue by gitCoy** [ElemeFE/react-amap#67]
我现在用到了这个函数，但是我发现我获取不到你的这个函数

**Comment by ioslh** [comment]
试试看[这个](https://github.com/ElemeFE/react-amap/issues/12)能不能解决你的问题

**Comment by gitCoy** [comment]
谢谢，原来可以在created里面直接获取到AMap对象！如果早先在文档里能看到就好了！总之完美解决
