### ISSUE TITLE
调用Marker原生moveAlong方法时出错

### ISSUE THREAD

**Issue by cnahliu** [ElemeFE/react-amap#68]
### react-amap version
 1.2.0 

### OS/Browers version
macOS/Chrome  62.0.3202.94 

### Reproduction Link

https://jsfiddle.net/cvt204g4/

### Steps to reproduce
Run 之后 查看控制台输出。
### What is Expected?
正常按轨迹移动。
### What is actually happening?
调用时出错。

**Comment by ioslh** [comment]
我在你那个基础上修改了一下。https://jsfiddle.net/ioslh/cvt204g4/1/

react-amap 没有对 moveAlong 方法进行包装，必须按照高德的要求来调用。它的第一个参数是路径，即坐标列表，每一个坐标都需要自己用 new AMap.LngLat 来创建。

react-amap 组件库里有些属性可以简略的写成`[lng, lat]` 的形式，最后组件内部还是会用 new AMap.LngLat 来创建。
