### ISSUE TITLE
infoWindow children 如果是react组件 则在编译打包后出现莫名奇妙的错乱

### ISSUE THREAD

**Issue by forstef** [ElemeFE/react-amap#70]
### OS/Browers version
win 7/版本 63.0.3239.84（正式版本） （64 位）

### Steps to reproduce
infoWindow children 如果是react组件
### What is Expected?
编译打包后不出现异常
### What is actually happening?
编译打包serve -s build后出现异常，开发环境npm start没有问题

**Comment by ioslh** [comment]
你好，用的打包工具是什么？具体错误信息是啥啊？

**Comment by forstef** [comment]
你好，有微信或者qq吗，我把出错的源代码给你看看

**Comment by forstef** [comment]
我是使用的material-ui@next这个库的脚手架create-react-app，里面的打包工具应该是webpack
初步确定是与material-ui@next这个库冲突了：
`<InfoWindow isCustom={false} offset={[0,-50]} events={this.infoWinEvents} autoMove={true} >
<Button onClick={() => {this.redirectTo(poiId)}}>查看详细信息</Button></InfoWindow>`

其中Button 是引入的material-ui@next的组件，这样打包过后的渲染会错乱，而把Button 改为button后，就不会。注：button不是material-ui@next的组件。

InfoWindow 的children只要出现material-ui@next的组件，webpack打包后渲染就会出现异常。

**Comment by ioslh** [comment]
好的感谢反馈，我会安装一下尝试重现一下这个问题

**Comment by ioslh** [comment]
还没到打包阶段，不过确实发现了一个问题。InfoWindow 里 Button 的 mousedown 事件没有触发，导致没有点击的波纹效果。

**Comment by ioslh** [comment]
没有复现你说的这个问题
