### ISSUE TITLE
ClusterProps需要增加renderCluserMarker

### ISSUE THREAD

**Issue by yejintao** [ElemeFE/react-amap#71]
### react-amap version
1.1.1

### OS/Browers version
macOS

### What is Expected?

需要定制CluserMarker的render，高德官方可以自己实现 renderCluserMarker， 发现代码中 ClusterProps 中被排除，导致定制无效。

建议增加上。

**Comment by ioslh** [comment]
收到，本周内完成~

**Comment by ioslh** [comment]
@yejintao 很抱歉因为工作原因，近几周没时间更新这个。如果你这个需求紧急，可以尝试写一个[自定义地图组件](https://elemefe.github.io/react-amap/articles/extend) 来实现，或者，欢迎给本仓库提交 PR。

**Comment by meitingshuoguo** [comment]
是高德地图把这个方法改名字了还是你们写错了。我在高德的文档上复制过来的是renderClusterMarker。但是死活不生效，找到源码，发现你们写的是renderCluserMarker。。。。。。
