### ISSUE TITLE
请教下，用marks设置icon不生效，文档说兼容高德官网所有属性,是用法有问题吗

### ISSUE THREAD

**Issue by finalljx** [ElemeFE/react-amap#74]
两种方式都试了分别在 
let gicon = new window.AMap.Icon({
                size: new AMap.Size(14, 14), // 图标大小
                image: '/dist/images/green.png',
                imageSize: new AMap.Size(14, 14)
            })
<Marks icon={gicon}></Marks>

第二种方法是通过 marks属性设置的
let marks = [] 
 m = {
                icon: new AMap.Icon({
                    size: new AMap.Size(14, 14), // 图标大小
                    image: "http://webapi.amap.com/theme/v1.3/images/newpc/way_btn2.png",
                    imageSize: new AMap.Size(14, 14)
                }),
                position: [marker.position[0], marker.position[1]],
                offset: new AMap.Pixel(-7, -7),
                zIndex: 101,
                extData: marker,
                gpsIndex
            };
marks.push(m)
<Marks marks={marks}></Marks>

### react-amap version
1.2.0

### OS/Browers version
 macOS/Chrome 53

**Comment by Ligengxin96** [comment]
同问,如何自定义Marker组件的图标,这个问题怎么被关闭了

**Comment by Symous** [comment]
@finalljx @Ligengxin96 老哥，你们解决了吗？

**Comment by Ligengxin96** [comment]
没有，没管了，反正也是玩具项目

**Comment by Ligengxin96** [comment]
> @finalljx @Ligengxin96 老哥，你们解决了吗？
没有，反正也是玩具项目，没管了

**Comment by linjinglan** [comment]
@Ligengxin96 @Symous @finalljx 
大佬们，解决了吗？markers设置icon

**Comment by Symous** [comment]
@linjinglan 需要使用render属性并返回一个方法，大致这样：
```js
<Markers
    markers={dataSource}
    render={()=> <img src={require('...')}/>}
/>
```

**Comment by linjinglan** [comment]
> @linjinglan 需要使用render属性并返回一个方法，大致这样：
> 
> ```js
> <Markers
>     markers={dataSource}
>     render={()=> <img src={require('...')}/>}
> />
> ```

谢谢，可以了。还有个问题，把地图范围缩小的时候，比如显示范围从一个城市放大到一个中国，然后那个marker图标漂移到海上了，不知道这是否正常，以及有没办法解决

**Comment by Symous** [comment]
@linjinglan 这个还真没注意到过，你自己解决一下吧，解决了在这里分享一下。

**Comment by linjinglan** [comment]
> @linjinglan 这个还真没注意到过，你自己解决一下吧，解决了在这里分享一下。

重新看了下文档，是我marker的offset没设置好导致的，设置了offset 就不飘移了
