### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'tagName' of null

### ISSUE THREAD

**Issue by mohong122** [ElemeFE/react-amap#75]
![image](https://user-images.githubusercontent.com/1935979/35469428-82957f5c-036f-11e8-88b5-14f845aa65d9.png)

```js
  <div style={{width: '200px', height: '200px'}}>
                <Map amapkey={"c6b7b02eaed5414c2627fd9a28242785"} />
            </div>

```

![image](https://user-images.githubusercontent.com/1935979/35469436-a7b5e574-036f-11e8-9579-cc9fc0ede510.png)

报错的原因是找不到上层的div，生成处div为null

### react-amap version
1.1.1 

### OS/Browers version
macOS/Chrome 63

**Comment by joshua7v** [comment]
我测试了下 无法重现

测试如图:

<img width="1440" alt="screen shot 2018-01-28 at 8 21 51 pm" src="https://user-images.githubusercontent.com/4159858/35481969-09178d32-0469-11e8-9500-190ed1dc2492.png">

**Comment by jasonlbw** [comment]
我也遇到了。。。

**Comment by ibreathebsb** [comment]
<img width="497" alt="屏幕快照 2019-08-14 下午12 07 06" src="https://user-images.githubusercontent.com/8876258/62993975-40995400-be8c-11e9-8ce3-bd7bf683d0e6.png">

我用了antd的loading，发现去掉后没问题了

**Comment by sir-ran** [comment]
经常有这个问题，，，请问解决了吗？

**Comment by LightningVII** [comment]
me too, what ? closed !!!!!!

**Comment by LightningVII** [comment]
when i use React.StrictMode, error tagName Cannot read property 'tagName' of null

**Comment by eugle** [comment]
还是有这个问题: Uncaught (in promise) TypeError: Cannot read property 'tagName' of null
2年了，没有人维护啊

**Comment by xj-xuejia** [comment]
疫情都进化到德尔塔、奥秘可容了，这个BUG还不修复

**Comment by hua-qi** [comment]
遇到同样的 bug 了，还没有修复吗

**Comment by yiminglu** [comment]
确实还会遇到同样的问题，绕过去的方案是包在一个div里面，且div给确定的 width 和 height，必须是px，不能是百分比。
可以通过minWidth/minHeight 来真正控制大小。

```
<div style={{ width: 100, height: window.innerHeight, minWidth: '100%', minHeight: '600px' }}>
        <Map />
</div>
```

**Comment by liwuchen** [comment]
我也遇到了
