### ISSUE TITLE
如何加载海量的多边形

### ISSUE THREAD

**Issue by LuoTuxiu** [ElemeFE/react-amap#78]
### What is Expected?

react的多边形变化能不重新渲染地图吗？

### What is actually happening?

加载上千条以上的polygon，react重绘地图的时候很慢很慢，有什么办法解决？

**Comment by ioslh** [comment]
加载大量的 `Polygon` 推荐直接使用高德的 API。如下：

```js
const mapEvents = {
  created (map) {
    // 这里调用高德的方法创建 Polygon
  }
}

// render 
<div>
  <Map events={mapEvents}/>
</div>
```
