### ISSUE TITLE
infowindow在iscustom设置为true时，自定义内容外有白框的问题

### ISSUE THREAD

**Issue by Croash** [ElemeFE/react-amap#80]
### react-amap version

infowindow在iscustom设置为true时，会将为infowindow添加类‘amap_markers_pop_window ’，导致会在自己添加的内容外有一个白框，希望可以自定义是否添加此类。

**Comment by Croash** [comment]
版本为 1.2.0
还有，即使在后面添加类名，仍然会被amap_markers_pop_window的样式覆盖
```
import { InfoWindow } from 'react-amap'
<InfoWindow 
  isCustom = {true}
  className = 'outInfo'
/>
```
outInfo 的部分样式会后面外链的amap_markers_pop_window覆盖

**Comment by ioslh** [comment]
很抱歉给你带来不便，你目前可以覆盖 `amap_markers_pop_window` 的样式试下

**Comment by Croash** [comment]
我通过对本地样式添加!important来处理好这个问题了
如果对InfoWindow.js内的setClassName()添加配置项，是否可以修正问题，个人想法
```
  setClassName() {
    let props = this.props
    let baseClsValue = ''
    if (props.isCustom === true) {
///这里加配置项
      baseClsValue = 'amap_markers_pop_window'
    }
    if (this.infoDOM) {
      // 刷新 className
      if ('className' in props && props.className) {
        baseClsValue += props.className
      }
      this.infoDOM.className = baseClsValue
    }
  }
```

**Comment by ioslh** [comment]
更新了 1.2.2 版本（https://github.com/ElemeFE/react-amap/blob/next/components/infowindow/index.js#L185）

**Comment by babycannotsay** [comment]
@ioslh 我觉得你更新的 逻辑判断并不好，，用户有可能把`className` 设置在`<InfoWindow>`的`children`里， 而不是作为`InfoWindow`的属性， 这时候 `isCustom` 是 `true` 还是`false` 都会有白框。这是 [demo](https://codepen.io/giggle/pen/KoKBqM)

**Comment by babycannotsay** [comment]
上面那个demo 给 `InfoWindow`随便加一个className  白框就没有了，会让觉得有点不可思议。
