### ISSUE TITLE
Polygon组件不支持多“岛”多边形

### ISSUE THREAD

**Issue by yhhcg** [ElemeFE/react-amap#83]

**Comment by yhhcg** [comment]
path数据为[[{longitude, latitude}], [], []]第一个元素为外多边形，之后的元素为‘岛’多边形的经纬度，只有一个岛多边形的情况下能画出

**Comment by ioslh** [comment]
高德地图只支持多边形和环多边形，你是说环多边形？
参考 http://lbs.amap.com/api/javascript-api/reference/overlay#polygon

**Comment by yhhcg** [comment]
对，“环”多边形，要求数组第一个元素为外多边形，其余为“岛”多边形,多岛画不出

**Comment by ioslh** [comment]
我[试了一下](https://jsfiddle.net/y9cv20cv/35/)，没问题的。要不你写个重现的例子？

**Comment by ioslh** [comment]
明白了，正在修复

**Comment by ioslh** [comment]
[1.2.3](https://www.npmjs.com/package/react-amap) fixed
