### ISSUE TITLE
您好，请问我如何在设置map属性layers之前获取到TileLayer对象的实例参数呢？

### ISSUE THREAD

**Issue by gitCoy** [ElemeFE/react-amap#84]
### Steps to reproduce
none
### What is Expected?
获取到：
var googleLayer = new AMap.TileLayer({
        getTileUrl: 'http://mt{1,2,3,0}.google.cn/vt/lyrs=s&hl=zh-CN&gl=cn&x=[x]&y=[y]&z=[z]&s=Galile'
    });//定义谷歌卫星切片图层
    var roadNetLayer = new AMap.TileLayer.RoadNet(); //定义一个路网图层
后调用这两个属性：
设置layers:[googleLayer,roadNetLayer] //设置图层
### What is actually happening?
我不知道怎么设置map的layers属性之前获取到参数对象实例！

**Comment by ghost** [comment]
请问是如何解决的呢

**Comment by gitCoy** [comment]
> 请问是如何解决的呢

不好意思，因为这个问题是18年的时候提出的了，我已经忘了当时怎么解决的了。
以后我会将问的问题跟进，将解决方案进行补充

**Comment by Thrashu** [comment]
给<Map>组件绑定一个key，通过setState的方式更新获取TileLayer的实例，
this.mapEvents = {
      created: (tool) => {
        console.log('mapTool',tool)
        self.mapTool = tool

       this.googleMapLayer = new  window.AMap.TileLayer({ //图层
         getTileUrl: 'http://mt{1,2,3,0}.google.cn/vt/lyrs=s&hl=zh-CN&gl=cn&x=[x]&y=[y]&z=[z]&s=Galile'
       });
        this.setState({key:'TileLayer'})
      }
    }

**Comment by Thrashu** [comment]
给组件绑定一个key，通过setState的方式更新获取TileLayer的实例
~~~js
this.mapEvents = {
created: (tool) => {
console.log('mapTool',tool)
self.mapTool = tool
   this.googleMapLayer = new  window.AMap.TileLayer({ //图层
     getTileUrl: 'http://mt{1,2,3,0}.google.cn/vt/lyrs=s&hl=zh-CN&gl=cn&x=[x]&y=[y]&z=[z]&s=Galile'
   });
    this.setState({key:'TileLayer'})
  }
}
