### ISSUE TITLE
发现Polyline path 更新不了的bug

### ISSUE THREAD

**Issue by exvu** [ElemeFE/react-amap#85]
**今天使用Polyline组件 ,通过将path的值放入state，通过向已有的state.path中push经纬度对象，再调用setState方法触发了render，但是Polyline组件的线没有改变。**

开始使用
```
this.setState({
     path:path
})
```

后面使用
```
this.setState({
     path:JSON.parse(JSON.stringify(path))
})

```
就成功了  

是不是Polyline是检查引用是否不相等才渲染界面？？

（不确定是不是我使用的问题 (*^__^*) 嘻嘻……）

**Comment by ioslh** [comment]
是检查引用的，参考[这里](https://github.com/ElemeFE/react-amap/blob/next/components/utils/withPropsReactive.js#L81)

**Comment by exvu** [comment]
@ioslh  MouseTool 不能删除标记点吗??

**Comment by ioslh** [comment]
没法删除，高德没有提供删除的方式。

不过如果要实现动态增删标记点可以使用 `Markers` 组件。

**Comment by exvu** [comment]
@ioslh 谢谢回答 希望以后MouseTool path能像react的state一样 而不是检查引用

**Comment by ioslh** [comment]
> 通过向已有的state.path中push经纬度对象，再调用setState方法

[React 官方建议别这么做](https://reactjs.org/docs/react-component.html#state)：

> Never mutate this.state directly, as calling setState() afterwards may replace the mutation you made. Treat this.state as if it were immutable.
