### ISSUE TITLE
Markers 的数据问题

### ISSUE THREAD

**Issue by MinHongwei** [ElemeFE/react-amap#88]
<Markers 
            markers={this.markers}
          />
markers 数据怎么去取出来？ 有没有不是随机生成 写死的。

**Comment by MinHongwei** [comment]
Uncaught Invalid Object: Pixel(NaN, NaN)   必须要放在constructor()  里面才不要报各种各样的错误吗？

**Comment by ioslh** [comment]
有错误重现链接或者代码片段吗？

**Comment by MinHongwei** [comment]
Uncaught Invalid Object: Pixel(NaN, NaN)

**Comment by MinHongwei** [comment]
https://codesandbox.io/s/lr5v9vyzp9

**Comment by MinHongwei** [comment]
```
const { itemList } = vrsmSite;
    const test = () => {
      console.log('itemList.length => ', itemList.length);
      if (itemList.length > 0) {
        console.log('itemList.length => ', itemList.length);
        const datasValue = itemList.map(d => ({
          position: {
            longitude: d.longitude,
            latitude: d.latitude,
          },
          myLabel: d.name,
          myIndex: d.id,
        }));
        return <HertMat makesData={datasValue} />;
      }
      return '';
    };
```

**Comment by MinHongwei** [comment]
我用这种方法写出来的，但是  点不会一来就有的，  而是要我鼠标放大 缩小一下，才会出来

**Comment by ioslh** [comment]
> https://codesandbox.io/s/lr5v9vyzp9

这个链接里的代码无法正确执行

**Comment by ioslh** [comment]
> markers 数据怎么去取出来？

这个可以参考 [这里的](https://elemefe.github.io/react-amap/components/markers) 的例子 `确定点击的是哪个坐标？`

**Comment by MinHongwei** [comment]
链接里面的代码 本来就没插件的

**Comment by ioslh** [comment]
给个可执行的重现链接？

**Comment by MinHongwei** [comment]
我问的是  我怎么定义这些数据，怎么去定义 markers  的数据

**Comment by ioslh** [comment]
也可以参考 https://elemefe.github.io/react-amap/components/markers 提到的例子。

**Comment by MinHongwei** [comment]
https://codesandbox.io/s/lr5v9vyzp9

**Comment by MinHongwei** [comment]
https://elemefe.github.io/react-amap/components/markers  这里的例子的标记点都是些死的，要不就是随机数。
