### ISSUE TITLE
AMap.MarkerClusterer 插件的 聚合点 样式修改不了

### ISSUE THREAD

**Issue by dbwamgod** [ElemeFE/react-amap#89]
我设置了 AMap.MarkerClusterer 构造函数 但是 样式 覆盖不了 出现了 重合 
该怎么办？

**Comment by ioslh** [comment]
有相关代码片段或者重现链接吗？

**Comment by dbwamgod** [comment]
```js
 let asd=new AMap.MarkerClusterer(this.mapInstance,allMarkers,{
                        gridSize:100,
                        renderCluserMarker:this._renderCluserMarker,
                        minClusterSize:2
                    });
```

我用这个覆盖不了 Markers 组件的 聚合点  会出现两个不同样式的 聚合点 
上面那个构造函数 我 是在 Markers 组件 events created里添加的

**Comment by ioslh** [comment]
请问你用的 react-amap 是什么版本？如果是 1.2.3 以下请升级，参考 #71 。

如果仍然不能解决麻烦再附上更详细的代码或者重现示例链接。我用最新的 1.2.3 版本试了下是没问题的
https://jsfiddle.net/y9cv20cv/60/

**Comment by dbwamgod** [comment]
说明文挡是不是没有更新啊？ 哈哈 能给个说明文档么

**Comment by ioslh** [comment]
是解决了吗？

**Comment by jiezai-007** [comment]
请问这个问题解决了吗？代码可以贴一下吗？

**Comment by dbwamgod** [comment]
看一下 git 作者 给回复了 你的版本要是 低的话  升级下  他添加了方法 可以 调用 高德 原有 自定义 样式API






在 2018-04-19 11:19:33，"DiligentGirl" <notifications@github.com> 写道：


请问这个问题解决了吗？代码可以贴一下吗？

**Comment by lemp001** [comment]
怎么解决的？大佬还能再贴一下吗？https://jsfiddle.net/y9cv20cv/60/ 这个打不开啊
