### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by ruicky** [ElemeFE/react-amap#9]
when i use this commpont, I get a error, it's ：
`window is not defined`

this is my code：
```
import React from 'react';
import { Map } from 'react-amap';


export default function MapView() {
  return (
    <div style={{ width: '600px', height: '500px' }}>
      <Map amapkey={'xxxx'} />
    </div>
  );
}

```

I hope you can reply to me、 Thank you.

**Comment by ioslh** [comment]
What browser are you using?and the version?

**Comment by ioslh** [comment]
This error seems not make sense, are you running this in a non-browser environment?

**Comment by ruicky** [comment]
when  i use isomorphic way to run project, it'e error.  :(

**Comment by ioslh** [comment]
I guess you are using SSR, so there are no variable 'window' in node environment. react-amap does not support SSR for now, sorry for that.
 I will consider support for it.

**Comment by ruicky** [comment]
You're right.
Hope to be able to support it as soon as possible.
 :)

**Comment by ioslh** [comment]
@ruicky Hi, I have upgrade `react-amap` to version [0.2.5](https://www.npmjs.com/package/react-amap), which we check if `window` exists before create map instance( and other related component), thus you can pass build process in your ssr project.

You are welcomed to download and try, glad to see your response.

**Comment by hjtgzh** [comment]
1、`let CustomMap`
2、`componentDidMount(){ CustomMap=require('react-amap').Map }`
3、在render里面使用：`<CustomMap />`
注：其他自定义的自行补充
