### ISSUE TITLE
Marker click事件中建议增加extData传入的数据作为参数

### ISSUE THREAD

**Issue by sam019** [ElemeFE/react-amap#90]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [ ] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### What is Expected?

Marker click事件的回调函数可以接收该Marker的extData作为参数
#### What is actually happening?
Marker click事件的回调函数只接受一个参数，而且通过e.F.extData获取的数据是首次渲染时的数据，数据变化后不会更新

**Comment by ioslh** [comment]
> 数据变化后不会更新

你的数据是怎么变化的？

你看我写的[这个例子](https://jsfiddle.net/y9cv20cv/61/)里没问题的
