### ISSUE TITLE
Marker在click事件里销毁当前实例，控制台报错

### ISSUE THREAD

**Issue by hashforu** [ElemeFE/react-amap#91]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [x] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### What is actually happening?
在Markers的点击事件中，使用react-router路由跳转离开当前页面，程序执行正常，但是会一直VM报错？请问是什么原因呢？

**Comment by hashforu** [comment]
您好，我发现只要在marker的点击事件中，销毁掉Amap组件，都会导致这种错误
[fiddle](https://jsfiddle.net/Lt7jm5ms/)

**Comment by ioslh** [comment]
纯粹使用高德 JSSDK 写了个[示例](https://jsfiddle.net/ioslh/b0qh6djL/1/)，发现也会出现这个问题。

暂不清楚原因，在跟高德的开发沟通。

**Comment by ioslh** [comment]
[1.2.4 更新](https://github.com/ElemeFE/react-amap/blob/next/components/utils/withPropsReactive.js#L97)解决了这个问题。
根据高德官方提供的思路是要在 timeout 里 destroy 地图。
如果还有其他问题，欢迎提供反馈~

**Comment by hashforu** [comment]
为大佬的效率疯狂打call，给你我的小星星。

**Comment by babycannotsay** [comment]
@ioslh  老哥，react-map 纸面版本更新到了1.2.5  实际上还是1.2.3啊，npm能不能publish一下最新的版本。你上面写的代码也没有生效、
