### ISSUE TITLE
如何确保useAMapUI加载成功

### ISSUE THREAD

**Issue by helloalexian** [ElemeFE/react-amap#92]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [x] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### Reproduce Example Link or Code Fragment
                    <Map amapkey={AMAP_KEY}
                         version={VERSION}
                         useAMapUI
                        // center={{longitude: amapLongitude, latitude: amapLatitude}}
                         zoom={12}
                         className={style.amap}
                    >
                    </Map>

#### What is Expected?
useAMapUI是否有相关的回调，可以提醒是否加载完毕？

#### What is actually happening?
useAMapUI应该是需要一小段时间的，如果在这一下端期间进入需要AMapUI的组件，会报相关AMapUI的undefined的错误

**Comment by ioslh** [comment]
已更新 [1.2.5](https://github.com/ElemeFE/react-amap/commit/0f46255ab5191d59184766bf379699a479030965)

**Comment by helloalexian** [comment]
Thank you!!!

**Comment by helloalexian** [comment]
使用您提供的回调方法还是会偶尔发生一些报错
报错内容：
Uncaught TypeError: PathSimplifier is not a constructor
![image](https://user-images.githubusercontent.com/36184988/39036267-8bbcc564-44af-11e8-92b1-e6f223512151.png)

![image](https://user-images.githubusercontent.com/36184988/39036231-76f26cba-44af-11e8-8526-5afc6cf3cbdb.png)

所以应该推测还是AMapUI资源没有加载完毕导致PathSimplifier找不到报错？

相关代码：
class AMap extends Component {
****

<Map
amapkey={AMAP_KEY}
version={VERSION}
useAMapUI={this.initAMapUICallback}
center={longitude: amapLongitude, latitude: amapLatitude} 
zoom={12}
className={style.amap}
>

![image](https://user-images.githubusercontent.com/36184988/39037455-2474c8b2-44b3-11e8-9434-f1bfd75da71a.png)

/>

    initAMapUICallback() {
        console.log("AMapUI Loaded Done");
        this.setState({
            amapUILoaded: true,
            displayPath: true
        });
    };
***
}


class PathSimplifier extends Component {
    constructor(props) {
        super(props);
            this.loadUI();
        }
    loadUI() {
        window.AMapUI.loadUI(['misc/PathSimplifier'], (PathSimplifier) => {
            let pathSimplifierIns = new PathSimplifier({
                zIndex: 100,
****************************************************************************************************
            });
        });
    }
}
![image](https://user-images.githubusercontent.com/36184988/39037069-fe2b83fe-44b1-11e8-9dff-fba2a1e12f2d.png)

**Comment by Croash** [comment]
@HelloAlexian 
试着把loadui() 放到componentDidMount里运行
```
componentDidMount() {
  this.loadUI()
}
```

**Comment by helloalexian** [comment]
@Croash 感谢，我试一下
