### ISSUE TITLE
希望可以指定api访问的协议（http、https）

### ISSUE THREAD

**Issue by destinyd** [ElemeFE/react-amap#95]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [x] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### Reproduce Example Link or Code Fragment
- react 16.3.0-rc.0
- react-amap 1.2.3
- Android Cordova

#### What is Expected?
代码编译后，放置在android的assets，WebView请求file://assets/page.html，以实现快速加载并执行。

#### What is actually happening?
加载高德webapi报错，因为协议不正确：
```
Failed to load resource: net::ERR_FILE_NOT_FOUND
file://webapi.amap.com/maps?v=1.4.4&key=xxx&callback=__amap_init_callback


Failed to load resource: net::ERR_FILE_NOT_FOUND
file://webapi.amap.com/ui/1.0/main-async.js
```

希望可以指定api访问的协议（http、https）。

**Comment by destinyd** [comment]
例子直接使用最简单的
```
render{return(<Map />)}
```
只要在本地访问都会出现

**Comment by ioslh** [comment]
更新了[ 1.2.6 版本](https://github.com/ElemeFE/react-amap/blob/next/components/utils/APILoader.js#L28)，可以使用 `protocol` 属性指定 API 加载的协议，你可以试试看。

```jsx
<Map protocol="http"/>
```

如有问题，欢迎随时提出。

**Comment by destinyd** [comment]
赞👍

**Comment by destinyd** [comment]
请求**webapi.amap.com/ui/1.0/main-async.js**依旧使用当前访问协议(file://)，导致未能正常使用。

**Comment by ioslh** [comment]
你没指定 protocol 属性吧。

取值逻辑是这样：
```js
protocol = props.protocol || window.location.protocol
```

**Comment by ioslh** [comment]
啊疏忽了，还有 amapui 的协议没改。

**Comment by ioslh** [comment]
已升级 1.2.7，统一了 protocol 的取值逻辑（[代码见这里](https://github.com/ElemeFE/react-amap/blob/next/components/utils/APILoader.js#L25)），你再试试。

**Comment by destinyd** [comment]
测试OK了
