### ISSUE TITLE
bug问题：A B两个页面都用了Map。从A页面进入B页面,B页面的拖拽效果失效。刷新B页面，拖拽效果才生效。

### ISSUE THREAD

**Issue by samsonCao** [ElemeFE/react-amap#96]
# **步骤1:进入A页面 。。。。**
A页面加载地图 核心代码如下
<Map amapkey={'key'}
                                 center={{longitude: state.lng, latitude: state.lat}}
                                 zoom={15}>
                                 <InfoWindow
                                    position={{longitude: state.lng, latitude: state.lat}}
                                    visible={state.address ? true : false}
                                    isCustom={false}
                                    content={`<h3 class='content-info'>${state.address}</h3>`}
                                    size={{width: 300, height: 45}}
                                 />
                            </Map>
￼A页面加载的localStorage如下 
_AMap_maintcvcg  
_AMap_data.tileKeys 
_AMap_AMap.CustomLayer
_AMap_cvector
_AMap_AMap.IndoorMap

# **步骤2：从A页面跳转到B页面。**
离开A页面时会把localStorage值清空 然后跳转B页面 此时跳转到B页面时加载的localStorage如下图
￼_AMap_AMap.ToolBar
_AMap_AMap.Geocoder
_AMap_data.tileKeys

# **步骤3：问题点：拖动小图标选址功能失效**

# **步骤4：刷新B页面 此时拖拽功能生效 加载的localStorage如下。**
_AMap_maintcvcg
_AMap_AMap.CustomLayer
_AMap_cvector
_AMap_AMap.IndoorMap
_AMap_AMap.ToolBar
_AMap_AMap.Geocoder
_AMap_data.tileKeys

# **步骤5：再从B页面回到A页面，加载的localStorage如下。**
_AMap_data.tileKeys

￼
B页面核心代码如下
import React, {Component} from "react"
import {connect} from 'react-redux'
import {Map, Marker} from 'react-amap';

class GetLonAndLatComponent extends React.Component {
     constructor() {
          super();
          const that = this;
          this.map = null;
          this.marker = null;
          this.geocoder = null;
          this.mapEvents = {
               created(map) {
                    that.map = map;
                    AMap.plugin('AMap.Geocoder', () => {
                         that.geocoder = new AMap.Geocoder({});
                    })
               },
               click(e) {
                    const lnglat = e.lnglat;

                    that.setState({
                         position: lnglat,
                    });
                    //输入地址点击地图获取经纬度 标记地址
                    that.geocoder.getLocation(that.props.address, function (status, result) {
                         if (status === 'complete' && result.info === 'OK') {
                              that.setState({
                                   position: result.geocodes[0].location,
                              });
                              that.props.callback(result);

                         }
                    });
               }
          };
          this.markerEvents = {
               created(map) {
                    that.map = map;
                    AMap.plugin('AMap.Geocoder', () => {
                         that.geocoder = new AMap.Geocoder({});
                    })
               },
               dragend: function (e) {
                    let lnglat = e.lnglat;

                    //拖拽获取地址和经纬度
                    that.geocoder && that.geocoder.getAddress(lnglat, (status, result) => {
                         if (status === 'complete') {
                              if (result.regeocode) {
                                   that.geocoder.getLocation(result.regeocode.formattedAddress, function (status, result) {

                                        if (status === 'complete' && result.info === 'OK') {
                                             that.props.callback(result);
                                        }
                                   });
                              }
                         }
                    });
               }
          };
          this.state = {
               position: {lat: 31.219705, lng: 121.411364},
          }
     }

     componentWillMount() {
          let position = this.props.position;
          if (position.lat == 0 || position.lng === 0 || !position.lat || !position.lng) {
               position = JSON.parse(localStorage.getItem('coords'))
          }
          this.setState({
               position: position
          })
     }

     componentWillUnmount() {
          localStorage.removeItem('_AMap_AMap.CustomLayer');
          localStorage.removeItem('_AMap_AMap.Geocoder');
          localStorage.removeItem('_AMap_AMap.IndoorMap');
          localStorage.removeItem('_AMap_AMap.ToolBar');
          localStorage.removeItem('_AMap_cvector');
          localStorage.removeItem('_AMap_data.tileKeys');
          localStorage.removeItem('_AMap_maintcvcg');
     }

     //需传入amapkey
     render() {
          return <Map center={this.state.position} events={this.mapEvents} zoom={14} plugins={['ToolBar']}>
               <Marker position={this.state.position} events={this.markerEvents} draggable={true}/>
          </Map>
     }
}

export default GetLonAndLatComponent;

**Comment by ioslh** [comment]
```js
      localStorage.removeItem('_AMap_AMap.CustomLayer');
      localStorage.removeItem('_AMap_AMap.Geocoder');
      localStorage.removeItem('_AMap_AMap.IndoorMap');
      localStorage.removeItem('_AMap_AMap.ToolBar');
      localStorage.removeItem('_AMap_cvector');
      localStorage.removeItem('_AMap_data.tileKeys');
      localStorage.removeItem('_AMap_maintcvcg');
```

这一系列是什么操作？为什么要这样做呢？

**Comment by samsonCao** [comment]
组件销毁的时候想要清除localStorage里面存的值。因别别的地方用不到了，不希望浏览器里面存很多没用的localStorage信息。即使不清除localStorage的这些值。拖拽同样没效果。我疑惑的点在于：拖拽功能为什么会失效？拖拽失效跟localStorage存的这些键值对有没有关系？为什么再次刷新页面拖拽功能就又生效了？

**Comment by ioslh** [comment]
> 拖拽失效跟localStorage存的这些键值对有没有关系

你把操作高德存的 localStorage 相关的代码注释掉试试？

**Comment by samsonCao** [comment]
其实我想说 这个localStorage 是我在进入页面加载Map 的过程中，自动生成的。并不是我添加上去的。刚刚测试了一下，确实跟这个localStorage没关系。问题是从不同的场景进来B页面，拖拽事件会失效，这就让人很费解。

**Comment by samsonCao** [comment]
`问题解决了` 方法不是很完美  但是可以用......把两个子组件Mraker 和 InfoWindow 写在同一个Map里面 封装成一个新的组件  调用的时候传入visible参数控制两个子组件显示隐藏就行了# ****
