### ISSUE TITLE
怎么使用高德地图中的对象呀～比如AMap.LngLat(11,20)

### ISSUE THREAD

**Issue by superWalnuts** [ElemeFE/react-amap#97]
怎么使用高德地图中的对象呀～比如AMap.LngLat(11,20)

**Comment by Croash** [comment]
可以直接调用AMap.LngLat(11,20)，AMap已经加载到window中了

**Comment by superWalnuts** [comment]
但是我这么写会报错， 'AMap' is not defined  no-undef
`this.markerEvents = {
      created: (markerInstance) => {
        let lngLat = AMap.LngLat(11,20);
        markerInstance.moveTo(lngLat,100);
      }
    }`

**Comment by superWalnuts** [comment]
找到问题了 得这么写
`        let lngLat = new window.AMap.LngLat(121,31);
`
