### ISSUE TITLE
我在react-amap中引入了高德的ui组件PathSimplifier，报错说mime类型不符，求问怎么解决

### ISSUE THREAD

**Issue by liyue118** [ElemeFE/react-amap#98]
如图，用PointSimplifier没有问题，用PathSimplifier有问题

紧急求救！！！

**Comment by ioslh** [comment]
图呢？

另外请尽量描述清楚你的问题，最好有在线重现示例或代码。

**Comment by liyue118** [comment]
@ioslh 

![Uploading TIM截图20180417094604.png…]()
这个是我引入misc/PointSimplifier的图，请求头没有问题，代码可以运行

**Comment by liyue118** [comment]
这个是请求misc/PointSimplifier的请求头，接口没有问题可以正常运转：
`Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
Cache-Control: public, max-age=0
Connection: keep-alive
Content-Encoding: gzip
**Content-Type: application/javascript; charset=UTF-8**
Date: Tue, 17 Apr 2018 01:33:20 GMT
EagleEye-TraceId: 0b8c0b7215239288007273797e43f1
Last-Modified: Wed, 11 Apr 2018 06:49:29 GMT
Server: Tengine/Aserver
Timing-Allow-Origin: *
Transfer-Encoding: chunked
Vary: Accept-Encoding
X-Powered-By: Express`

这个是misc/PathSimplifier的请求头，可以看到多了一个安全验证的限制，浏览器报错了。
`Access-Control-Allow-Headers: Content-Type
Access-Control-Allow-Methods: *
Access-Control-Allow-Origin: *
Connection: keep-alive
Content-Length: 168
Content-Security-Policy: default-src 'self'
Content-Type: text/html; charset=utf-8
Date: Tue, 17 Apr 2018 01:33:20 GMT
Server: Tengine/Aserver
**X-Content-Type-Options: nosniff**
X-Powered-By: Express`

报错内容：Refused to execute script from 'http://webapi.amap.com/ui/1.0/misc/PathSimplifier.js?v=1.0.11' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

@ioslh

**Comment by ioslh** [comment]
`http://webapi.amap.com/ui/1.0/misc/PathSimplifier.js?v=1.0.11` 这个地址 404 了，你是怎么加载的，检查下是不是加载路径写错了。

**Comment by ioslh** [comment]
就是路径错了，正确的是`http://webapi.amap.com/ui/1.0/ui/misc/PathSimplifier.js?v=1.0.11`，你看看是怎么加载的。

**Comment by liyue118** [comment]
@ioslh  解决叻！感恩！另外问一下地图自定义模板除了现在有的，啥时候支持darkblue样式啊？

**Comment by ioslh** [comment]
已经支持了啊。

```jsx
<Map mapStyle={'amap://styles/darkblue'}/>
```

**Comment by liyue118** [comment]
@ioslh  okok
