### ISSUE TITLE
获取CitySearch等其他插件

### ISSUE THREAD

**Issue by helloalexian** [ElemeFE/react-amap#99]
+ [x] 我已经搜索过 issue，没有类似的问题，或者类似的问题仍然没有解决方案。
+ [x] 我已经搜索过[文档](https://elemefe.github.io/react-amap/articles/start)，并且仍然没有找到解决方案。
+ [x] 我写了个问题重现的例子，链接或者代码将会贴在下面。

#### Reproduce Example Link or Code Fragment

        window.AMap.plugin('AMap.CitySearch', () => {
            let citySearch = new AMap.CitySearch();
            citySearch.getLocalCity(function (status, result) {
                if (status === 'complete' && result.info === 'OK') {
                    if (result && result.city && result.bounds) {
                        console.log("citySearch", result.city);

                        // var cityinfo = result.city;
                        // var citybounds = result.bounds;
                    }
                } else {
                    console.log("citySearch", result.info);
                }
            })
        });

https://lbs.amap.com/api/javascript-api/reference/location#m_AMap.CitySearch

#### What is Expected?

目前通过window查询能够使用的plugin基本能够满足大多数的需求，但是有小部分个性化的功能需要用到高德其他的插件，例如现在的CtiySearch。

如何能够通过其他方法加载到CtiySearch等插件？

目前主要是需要通过CtiySearch获取到用户ip地址并得到返回的定位信息

#### What is actually happening?

Uncaught TypeError: AMap.CitySearch is not a constructor

**Comment by ioslh** [comment]
我试了下你的代码是没问题的。https://jsfiddle.net/y9cv20cv/102/

你试试把

```js
let citySearch = new AMap.CitySearch();
```

改成

```js
let citySearch = new window.AMap.CitySearch();
```

**Comment by helloalexian** [comment]
感谢，完美解决！
